if (blockId.includes("scaffolding")) {
    //足場
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["stability"=0] run setblock ${x} ${y} ${z} ${blockId} ["stability"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["stability"=1] run setblock ${x} ${y} ${z} ${blockId} ["stability"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["stability"=2] run setblock ${x} ${y} ${z} ${blockId} ["stability"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["stability"=3] run setblock ${x} ${y} ${z} ${blockId} ["stability"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["stability"=4] run setblock ${x} ${y} ${z} ${blockId} ["stability"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["stability"=5] run setblock ${x} ${y} ${z} ${blockId} ["stability"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["stability"=6] run setblock ${x} ${y} ${z} ${blockId} ["stability"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["stability"=7] run setblock ${x} ${y} ${z} ${blockId} ["stability"=0]`)
}
else if (blockId.includes("stonecutter_block") || blockId.includes("anvil") || blockId.includes("pumpkin")) {
    //ストーンカッター｜金床｜カボチャ｜かまど類
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["minecraft:cardinal_direction"="north"] run setblock ${x} ${y} ${z} ${blockId} ["minecraft:cardinal_direction"="east"]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["minecraft:cardinal_direction"="south"] run setblock ${x} ${y} ${z} ${blockId} ["minecraft:cardinal_direction"="east"]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["minecraft:cardinal_direction"="east"] run setblock ${x} ${y} ${z} ${blockId} ["minecraft:cardinal_direction"="east"]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["minecraft:cardinal_direction"="west"] run setblock ${x} ${y} ${z} ${blockId} ["minecraft:cardinal_direction"="east"]`)
}
else if (blockId.includes("end_portal_frame")) {
    //エンドポータルフレーム
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["minecraft:cardinal_direction"="north","end_portal_eye_bit"=false] run setblock ${x} ${y} ${z} ${blockId} ["minecraft:cardinal_direction"="east","end_portal_eye_bit"=false]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["minecraft:cardinal_direction"="north","end_portal_eye_bit"=true] run setblock ${x} ${y} ${z} ${blockId} ["minecraft:cardinal_direction"="east","end_portal_eye_bit"=true]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["minecraft:cardinal_direction"="south","end_portal_eye_bit"=false] run setblock ${x} ${y} ${z} ${blockId} ["minecraft:cardinal_direction"="east","end_portal_eye_bit"=false]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["minecraft:cardinal_direction"="south","end_portal_eye_bit"=true] run setblock ${x} ${y} ${z} ${blockId} ["minecraft:cardinal_direction"="east","end_portal_eye_bit"=true]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["minecraft:cardinal_direction"="east","end_portal_eye_bit"=false] run setblock ${x} ${y} ${z} ${blockId} ["minecraft:cardinal_direction"="east","end_portal_eye_bit"=false]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["minecraft:cardinal_direction"="east","end_portal_eye_bit"=true] run setblock ${x} ${y} ${z} ${blockId} ["minecraft:cardinal_direction"="east","end_portal_eye_bit"=true]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["minecraft:cardinal_direction"="west","end_portal_eye_bit"=false] run setblock ${x} ${y} ${z} ${blockId} ["minecraft:cardinal_direction"="east","end_portal_eye_bit"=false]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["minecraft:cardinal_direction"="west","end_portal_eye_bit"=true] run setblock ${x} ${y} ${z} ${blockId} ["minecraft:cardinal_direction"="east","end_portal_eye_bit"=true]`)
}
else if (blockId.includes("piston") || blockId.includes("end_rod") || blockId.includes("lightning_rod")) {
    //ピストン｜エンドロッド｜避雷針
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["facing_direction"=0] run setblock ${x} ${y} ${z} ${blockId} ["facing_direction"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["facing_direction"=1] run setblock ${x} ${y} ${z} ${blockId} ["facing_direction"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["facing_direction"=2] run setblock ${x} ${y} ${z} ${blockId} ["facing_direction"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["facing_direction"=3] run setblock ${x} ${y} ${z} ${blockId} ["facing_direction"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["facing_direction"=4] run setblock ${x} ${y} ${z} ${blockId} ["facing_direction"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["facing_direction"=5] run setblock ${x} ${y} ${z} ${blockId} ["facing_direction"=0]`)
}
else if (blockId.includes("cauldron")) {
    //大釜
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["cauldron_liquid"="water","fill_level"=0] run setblock ${x} ${y} ${z} ${blockId} ["cauldron_liquid"="water","fill_level"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["cauldron_liquid"="water","fill_level"=1] run setblock ${x} ${y} ${z} ${blockId} ["cauldron_liquid"="water","fill_level"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["cauldron_liquid"="water","fill_level"=2] run setblock ${x} ${y} ${z} ${blockId} ["cauldron_liquid"="water","fill_level"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["cauldron_liquid"="water","fill_level"=3] run setblock ${x} ${y} ${z} ${blockId} ["cauldron_liquid"="water","fill_level"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["cauldron_liquid"="water","fill_level"=4] run setblock ${x} ${y} ${z} ${blockId} ["cauldron_liquid"="water","fill_level"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["cauldron_liquid"="water","fill_level"=5] run setblock ${x} ${y} ${z} ${blockId} ["cauldron_liquid"="water","fill_level"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["cauldron_liquid"="water","fill_level"=6] run setblock ${x} ${y} ${z} ${blockId} ["cauldron_liquid"="water","fill_level"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["cauldron_liquid"="lava","fill_level"=0] run setblock ${x} ${y} ${z} ${blockId} ["cauldron_liquid"="lava","fill_level"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["cauldron_liquid"="lava","fill_level"=1] run setblock ${x} ${y} ${z} ${blockId} ["cauldron_liquid"="lava","fill_level"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["cauldron_liquid"="lava","fill_level"=2] run setblock ${x} ${y} ${z} ${blockId} ["cauldron_liquid"="lava","fill_level"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["cauldron_liquid"="lava","fill_level"=3] run setblock ${x} ${y} ${z} ${blockId} ["cauldron_liquid"="lava","fill_level"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["cauldron_liquid"="lava","fill_level"=4] run setblock ${x} ${y} ${z} ${blockId} ["cauldron_liquid"="lava","fill_level"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["cauldron_liquid"="lava","fill_level"=5] run setblock ${x} ${y} ${z} ${blockId} ["cauldron_liquid"="lava","fill_level"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["cauldron_liquid"="lava","fill_level"=6] run setblock ${x} ${y} ${z} ${blockId} ["cauldron_liquid"="lava","fill_level"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["cauldron_liquid"="powder_snow","fill_level"=0] run setblock ${x} ${y} ${z} ${blockId} ["cauldron_liquid"="powder_snow","fill_level"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["cauldron_liquid"="powder_snow","fill_level"=1] run setblock ${x} ${y} ${z} ${blockId} ["cauldron_liquid"="powder_snow","fill_level"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["cauldron_liquid"="powder_snow","fill_level"=2] run setblock ${x} ${y} ${z} ${blockId} ["cauldron_liquid"="powder_snow","fill_level"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["cauldron_liquid"="powder_snow","fill_level"=3] run setblock ${x} ${y} ${z} ${blockId} ["cauldron_liquid"="powder_snow","fill_level"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["cauldron_liquid"="powder_snow","fill_level"=4] run setblock ${x} ${y} ${z} ${blockId} ["cauldron_liquid"="powder_snow","fill_level"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["cauldron_liquid"="powder_snow","fill_level"=5] run setblock ${x} ${y} ${z} ${blockId} ["cauldron_liquid"="powder_snow","fill_level"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["cauldron_liquid"="powder_snow","fill_level"=6] run setblock ${x} ${y} ${z} ${blockId} ["cauldron_liquid"="powder_snow","fill_level"=0]`)
}
else if (blockId.includes("observer")) {
    //オブザーバー
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["minecraft:facing_direction"="north","powered_bit"=false] run setblock ${x} ${y} ${z} ${blockId} ["minecraft:facing_direction"="east","powered_bit"=false]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["minecraft:facing_direction"="north","powered_bit"=true] run setblock ${x} ${y} ${z} ${blockId} ["minecraft:facing_direction"="east","powered_bit"=true]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["minecraft:facing_direction"="south","powered_bit"=false] run setblock ${x} ${y} ${z} ${blockId} ["minecraft:facing_direction"="east","powered_bit"=false]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["minecraft:facing_direction"="south","powered_bit"=true] run setblock ${x} ${y} ${z} ${blockId} ["minecraft:facing_direction"="east","powered_bit"=true]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["minecraft:facing_direction"="east","powered_bit"=false] run setblock ${x} ${y} ${z} ${blockId} ["minecraft:facing_direction"="east","powered_bit"=false]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["minecraft:facing_direction"="east","powered_bit"=true] run setblock ${x} ${y} ${z} ${blockId} ["minecraft:facing_direction"="east","powered_bit"=true]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["minecraft:facing_direction"="west","powered_bit"=false] run setblock ${x} ${y} ${z} ${blockId} ["minecraft:facing_direction"="east","powered_bit"=false]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["minecraft:facing_direction"="west","powered_bit"=true] run setblock ${x} ${y} ${z} ${blockId} ["minecraft:facing_direction"="east","powered_bit"=true]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["minecraft:facing_direction"="up","powered_bit"=false] run setblock ${x} ${y} ${z} ${blockId} ["minecraft:facing_direction"="east","powered_bit"=false]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["minecraft:facing_direction"="up","powered_bit"=true] run setblock ${x} ${y} ${z} ${blockId} ["minecraft:facing_direction"="east","powered_bit"=true]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["minecraft:facing_direction"="down","powered_bit"=false] run setblock ${x} ${y} ${z} ${blockId} ["minecraft:facing_direction"="east","powered_bit"=false]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["minecraft:facing_direction"="down","powered_bit"=true] run setblock ${x} ${y} ${z} ${blockId} ["minecraft:facing_direction"="east","powered_bit"=true]`)
}
else if (blockId.includes("stairs")) {
    //階段ブロック
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["weirdo_direction"=0,"upside_down_bit"=false] run setblock ${x} ${y} ${z} ${blockId} ["weirdo_direction"=0,"upside_down_bit"=false]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["weirdo_direction"=0,"upside_down_bit"=true] run setblock ${x} ${y} ${z} ${blockId} ["weirdo_direction"=0,"upside_down_bit"=true]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["weirdo_direction"=1,"upside_down_bit"=false] run setblock ${x} ${y} ${z} ${blockId} ["weirdo_direction"=0,"upside_down_bit"=false]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["weirdo_direction"=1,"upside_down_bit"=true] run setblock ${x} ${y} ${z} ${blockId} ["weirdo_direction"=0,"upside_down_bit"=true]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["weirdo_direction"=2,"upside_down_bit"=false] run setblock ${x} ${y} ${z} ${blockId} ["weirdo_direction"=0,"upside_down_bit"=false]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["weirdo_direction"=2,"upside_down_bit"=true] run setblock ${x} ${y} ${z} ${blockId} ["weirdo_direction"=0,"upside_down_bit"=true]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["weirdo_direction"=3,"upside_down_bit"=false] run setblock ${x} ${y} ${z} ${blockId} ["weirdo_direction"=0,"upside_down_bit"=false]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["weirdo_direction"=3,"upside_down_bit"=true] run setblock ${x} ${y} ${z} ${blockId} ["weirdo_direction"=0,"upside_down_bit"=true]`)
}
else if (blockId.includes("cocoa")) {
    //カカオの実
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["direction"=0,"age"=0] run setblock ${x} ${y} ${z} ${blockId} ["direction"=0,"age"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["direction"=0,"age"=1] run setblock ${x} ${y} ${z} ${blockId} ["direction"=0,"age"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["direction"=0,"age"=2] run setblock ${x} ${y} ${z} ${blockId} ["direction"=0,"age"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["direction"=1,"age"=0] run setblock ${x} ${y} ${z} ${blockId} ["direction"=0,"age"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["direction"=1,"age"=1] run setblock ${x} ${y} ${z} ${blockId} ["direction"=0,"age"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["direction"=1,"age"=2] run setblock ${x} ${y} ${z} ${blockId} ["direction"=0,"age"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["direction"=2,"age"=0] run setblock ${x} ${y} ${z} ${blockId} ["direction"=0,"age"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["direction"=2,"age"=1] run setblock ${x} ${y} ${z} ${blockId} ["direction"=0,"age"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["direction"=2,"age"=2] run setblock ${x} ${y} ${z} ${blockId} ["direction"=0,"age"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["direction"=3,"age"=0] run setblock ${x} ${y} ${z} ${blockId} ["direction"=0,"age"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["direction"=3,"age"=1] run setblock ${x} ${y} ${z} ${blockId} ["direction"=0,"age"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["direction"=3,"age"=2] run setblock ${x} ${y} ${z} ${blockId} ["direction"=0,"age"=0]`)
}
else if (blockId.includes("bell")) {
    //鐘
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["direction"=0,"attachment"="hanging","toggle_bit"=false] run setblock ${x} ${y} ${z} ${blockId} ["direction"=0,"attachment"="hanging","toggle_bit"=false]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["direction"=0,"attachment"="hanging","toggle_bit"=true] run setblock ${x} ${y} ${z} ${blockId} ["direction"=0,"attachment"="hanging","toggle_bit"=true]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["direction"=1,"attachment"="hanging","toggle_bit"=false] run setblock ${x} ${y} ${z} ${blockId} ["direction"=0,"attachment"="hanging","toggle_bit"=false]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["direction"=1,"attachment"="hanging","toggle_bit"=true] run setblock ${x} ${y} ${z} ${blockId} ["direction"=0,"attachment"="hanging","toggle_bit"=true]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["direction"=2,"attachment"="hanging","toggle_bit"=false] run setblock ${x} ${y} ${z} ${blockId} ["direction"=0,"attachment"="hanging","toggle_bit"=false]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["direction"=2,"attachment"="hanging","toggle_bit"=true] run setblock ${x} ${y} ${z} ${blockId} ["direction"=0,"attachment"="hanging","toggle_bit"=true]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["direction"=3,"attachment"="hanging","toggle_bit"=false] run setblock ${x} ${y} ${z} ${blockId} ["direction"=0,"attachment"="hanging","toggle_bit"=false]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["direction"=3,"attachment"="hanging","toggle_bit"=true] run setblock ${x} ${y} ${z} ${blockId} ["direction"=0,"attachment"="hanging","toggle_bit"=true]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["direction"=0,"attachment"="multiple","toggle_bit"=false] run setblock ${x} ${y} ${z} ${blockId} ["direction"=0,"attachment"="multiple","toggle_bit"=false]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["direction"=0,"attachment"="multiple","toggle_bit"=true] run setblock ${x} ${y} ${z} ${blockId} ["direction"=0,"attachment"="multiple","toggle_bit"=true]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["direction"=1,"attachment"="multiple","toggle_bit"=false] run setblock ${x} ${y} ${z} ${blockId} ["direction"=0,"attachment"="multiple","toggle_bit"=false]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["direction"=1,"attachment"="multiple","toggle_bit"=true] run setblock ${x} ${y} ${z} ${blockId} ["direction"=0,"attachment"="multiple","toggle_bit"=true]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["direction"=2,"attachment"="multiple","toggle_bit"=false] run setblock ${x} ${y} ${z} ${blockId} ["direction"=0,"attachment"="multiple","toggle_bit"=false]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["direction"=2,"attachment"="multiple","toggle_bit"=true] run setblock ${x} ${y} ${z} ${blockId} ["direction"=0,"attachment"="multiple","toggle_bit"=true]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["direction"=3,"attachment"="multiple","toggle_bit"=false] run setblock ${x} ${y} ${z} ${blockId} ["direction"=0,"attachment"="multiple","toggle_bit"=false]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["direction"=3,"attachment"="multiple","toggle_bit"=true] run setblock ${x} ${y} ${z} ${blockId} ["direction"=0,"attachment"="multiple","toggle_bit"=true]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["direction"=0,"attachment"="side","toggle_bit"=false] run setblock ${x} ${y} ${z} ${blockId} ["direction"=0,"attachment"="side","toggle_bit"=false]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["direction"=0,"attachment"="side","toggle_bit"=true] run setblock ${x} ${y} ${z} ${blockId} ["direction"=0,"attachment"="side","toggle_bit"=true]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["direction"=1,"attachment"="side","toggle_bit"=false] run setblock ${x} ${y} ${z} ${blockId} ["direction"=0,"attachment"="side","toggle_bit"=false]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["direction"=1,"attachment"="side","toggle_bit"=true] run setblock ${x} ${y} ${z} ${blockId} ["direction"=0,"attachment"="side","toggle_bit"=true]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["direction"=2,"attachment"="side","toggle_bit"=false] run setblock ${x} ${y} ${z} ${blockId} ["direction"=0,"attachment"="side","toggle_bit"=false]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["direction"=2,"attachment"="side","toggle_bit"=true] run setblock ${x} ${y} ${z} ${blockId} ["direction"=0,"attachment"="side","toggle_bit"=true]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["direction"=3,"attachment"="side","toggle_bit"=false] run setblock ${x} ${y} ${z} ${blockId} ["direction"=0,"attachment"="side","toggle_bit"=false]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["direction"=3,"attachment"="side","toggle_bit"=true] run setblock ${x} ${y} ${z} ${blockId} ["direction"=0,"attachment"="side","toggle_bit"=true]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["direction"=0,"attachment"="standing","toggle_bit"=false] run setblock ${x} ${y} ${z} ${blockId} ["direction"=0,"attachment"="standing","toggle_bit"=false]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["direction"=0,"attachment"="standing","toggle_bit"=true] run setblock ${x} ${y} ${z} ${blockId} ["direction"=0,"attachment"="standing","toggle_bit"=true]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["direction"=1,"attachment"="standing","toggle_bit"=false] run setblock ${x} ${y} ${z} ${blockId} ["direction"=0,"attachment"="standing","toggle_bit"=false]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["direction"=1,"attachment"="standing","toggle_bit"=true] run setblock ${x} ${y} ${z} ${blockId} ["direction"=0,"attachment"="standing","toggle_bit"=true]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["direction"=2,"attachment"="standing","toggle_bit"=false] run setblock ${x} ${y} ${z} ${blockId} ["direction"=0,"attachment"="standing","toggle_bit"=false]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["direction"=2,"attachment"="standing","toggle_bit"=true] run setblock ${x} ${y} ${z} ${blockId} ["direction"=0,"attachment"="standing","toggle_bit"=true]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["direction"=3,"attachment"="standing","toggle_bit"=false] run setblock ${x} ${y} ${z} ${blockId} ["direction"=0,"attachment"="standing","toggle_bit"=false]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["direction"=3,"attachment"="standing","toggle_bit"=true] run setblock ${x} ${y} ${z} ${blockId} ["direction"=0,"attachment"="standing","toggle_bit"=true]`)
}
else if (blockId.includes("torch")) {
    //トーチ
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["torch_facing_direction"="north"] run setblock ${x} ${y} ${z} ${blockId} ["torch_facing_direction"="east"]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["torch_facing_direction"="south"] run setblock ${x} ${y} ${z} ${blockId} ["torch_facing_direction"="east"]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["torch_facing_direction"="east"] run setblock ${x} ${y} ${z} ${blockId} ["torch_facing_direction"="east"]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["torch_facing_direction"="west"] run setblock ${x} ${y} ${z} ${blockId} ["torch_facing_direction"="east"]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["torch_facing_direction"="up"] run setblock ${x} ${y} ${z} ${blockId} ["torch_facing_direction"="east"]`)
}
else if (blockId.includes("pumpkin_stem")) {
    //カボチャの種
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["facing_direction"=0,"growth"=0] run setblock ${x} ${y} ${z} ${blockId} ["facing_direction"=0,"growth"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["facing_direction"=0,"growth"=1] run setblock ${x} ${y} ${z} ${blockId} ["facing_direction"=0,"growth"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["facing_direction"=0,"growth"=2] run setblock ${x} ${y} ${z} ${blockId} ["facing_direction"=0,"growth"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["facing_direction"=0,"growth"=3] run setblock ${x} ${y} ${z} ${blockId} ["facing_direction"=0,"growth"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["facing_direction"=0,"growth"=4] run setblock ${x} ${y} ${z} ${blockId} ["facing_direction"=0,"growth"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["facing_direction"=0,"growth"=5] run setblock ${x} ${y} ${z} ${blockId} ["facing_direction"=0,"growth"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["facing_direction"=0,"growth"=6] run setblock ${x} ${y} ${z} ${blockId} ["facing_direction"=0,"growth"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["facing_direction"=0,"growth"=7] run setblock ${x} ${y} ${z} ${blockId} ["facing_direction"=0,"growth"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["facing_direction"=1,"growth"=0] run setblock ${x} ${y} ${z} ${blockId} ["facing_direction"=1,"growth"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["facing_direction"=1,"growth"=1] run setblock ${x} ${y} ${z} ${blockId} ["facing_direction"=1,"growth"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["facing_direction"=1,"growth"=2] run setblock ${x} ${y} ${z} ${blockId} ["facing_direction"=1,"growth"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["facing_direction"=1,"growth"=3] run setblock ${x} ${y} ${z} ${blockId} ["facing_direction"=1,"growth"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["facing_direction"=1,"growth"=4] run setblock ${x} ${y} ${z} ${blockId} ["facing_direction"=1,"growth"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["facing_direction"=1,"growth"=5] run setblock ${x} ${y} ${z} ${blockId} ["facing_direction"=1,"growth"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["facing_direction"=1,"growth"=6] run setblock ${x} ${y} ${z} ${blockId} ["facing_direction"=1,"growth"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["facing_direction"=1,"growth"=7] run setblock ${x} ${y} ${z} ${blockId} ["facing_direction"=1,"growth"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["facing_direction"=2,"growth"=0] run setblock ${x} ${y} ${z} ${blockId} ["facing_direction"=2,"growth"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["facing_direction"=2,"growth"=1] run setblock ${x} ${y} ${z} ${blockId} ["facing_direction"=2,"growth"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["facing_direction"=2,"growth"=2] run setblock ${x} ${y} ${z} ${blockId} ["facing_direction"=2,"growth"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["facing_direction"=2,"growth"=3] run setblock ${x} ${y} ${z} ${blockId} ["facing_direction"=2,"growth"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["facing_direction"=2,"growth"=4] run setblock ${x} ${y} ${z} ${blockId} ["facing_direction"=2,"growth"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["facing_direction"=2,"growth"=5] run setblock ${x} ${y} ${z} ${blockId} ["facing_direction"=2,"growth"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["facing_direction"=2,"growth"=6] run setblock ${x} ${y} ${z} ${blockId} ["facing_direction"=2,"growth"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["facing_direction"=2,"growth"=7] run setblock ${x} ${y} ${z} ${blockId} ["facing_direction"=2,"growth"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["facing_direction"=3,"growth"=0] run setblock ${x} ${y} ${z} ${blockId} ["facing_direction"=3,"growth"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["facing_direction"=3,"growth"=1] run setblock ${x} ${y} ${z} ${blockId} ["facing_direction"=3,"growth"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["facing_direction"=3,"growth"=2] run setblock ${x} ${y} ${z} ${blockId} ["facing_direction"=3,"growth"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["facing_direction"=3,"growth"=3] run setblock ${x} ${y} ${z} ${blockId} ["facing_direction"=3,"growth"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["facing_direction"=3,"growth"=4] run setblock ${x} ${y} ${z} ${blockId} ["facing_direction"=3,"growth"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["facing_direction"=3,"growth"=5] run setblock ${x} ${y} ${z} ${blockId} ["facing_direction"=3,"growth"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["facing_direction"=3,"growth"=6] run setblock ${x} ${y} ${z} ${blockId} ["facing_direction"=3,"growth"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["facing_direction"=3,"growth"=7] run setblock ${x} ${y} ${z} ${blockId} ["facing_direction"=3,"growth"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["facing_direction"=4,"growth"=0] run setblock ${x} ${y} ${z} ${blockId} ["facing_direction"=4,"growth"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["facing_direction"=4,"growth"=1] run setblock ${x} ${y} ${z} ${blockId} ["facing_direction"=4,"growth"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["facing_direction"=4,"growth"=2] run setblock ${x} ${y} ${z} ${blockId} ["facing_direction"=4,"growth"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["facing_direction"=4,"growth"=3] run setblock ${x} ${y} ${z} ${blockId} ["facing_direction"=4,"growth"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["facing_direction"=4,"growth"=4] run setblock ${x} ${y} ${z} ${blockId} ["facing_direction"=4,"growth"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["facing_direction"=4,"growth"=5] run setblock ${x} ${y} ${z} ${blockId} ["facing_direction"=4,"growth"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["facing_direction"=4,"growth"=6] run setblock ${x} ${y} ${z} ${blockId} ["facing_direction"=4,"growth"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["facing_direction"=4,"growth"=7] run setblock ${x} ${y} ${z} ${blockId} ["facing_direction"=4,"growth"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["facing_direction"=5,"growth"=0] run setblock ${x} ${y} ${z} ${blockId} ["facing_direction"=5,"growth"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["facing_direction"=5,"growth"=1] run setblock ${x} ${y} ${z} ${blockId} ["facing_direction"=5,"growth"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["facing_direction"=5,"growth"=2] run setblock ${x} ${y} ${z} ${blockId} ["facing_direction"=5,"growth"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["facing_direction"=5,"growth"=3] run setblock ${x} ${y} ${z} ${blockId} ["facing_direction"=5,"growth"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["facing_direction"=5,"growth"=4] run setblock ${x} ${y} ${z} ${blockId} ["facing_direction"=5,"growth"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["facing_direction"=5,"growth"=5] run setblock ${x} ${y} ${z} ${blockId} ["facing_direction"=5,"growth"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["facing_direction"=5,"growth"=6] run setblock ${x} ${y} ${z} ${blockId} ["facing_direction"=5,"growth"=0]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["facing_direction"=5,"growth"=7] run setblock ${x} ${y} ${z} ${blockId} ["facing_direction"=5,"growth"=0]`)
}
else if (blockId.includes("turtle_egg")) {
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["turtle_egg_count"="one_egg","cracked_state"="no_cracks"] run setblock ${x} ${y} ${z} ${blockId} ["turtle_egg_count"="one_egg","cracked_state"="no_cracks"]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["turtle_egg_count"="one_egg","cracked_state"="cracks"] run setblock ${x} ${y} ${z} ${blockId} ["turtle_egg_count"="one_egg","cracked_state"="cracks"]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["turtle_egg_count"="one_egg","cracked_state"="max_cracks"] run setblock ${x} ${y} ${z} ${blockId} ["turtle_egg_count"="one_egg","cracked_state"="max_cracks"]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["turtle_egg_count"="two_egg","cracked_state"="no_cracks"] run setblock ${x} ${y} ${z} ${blockId} ["turtle_egg_count"="one_egg","cracked_state"="no_cracks"]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["turtle_egg_count"="two_egg","cracked_state"="cracks"] run setblock ${x} ${y} ${z} ${blockId} ["turtle_egg_count"="one_egg","cracked_state"="cracks"]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["turtle_egg_count"="two_egg","cracked_state"="max_cracks"] run setblock ${x} ${y} ${z} ${blockId} ["turtle_egg_count"="one_egg","cracked_state"="max_cracks"]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["turtle_egg_count"="three_egg","cracked_state"="no_cracks"] run setblock ${x} ${y} ${z} ${blockId} ["turtle_egg_count"="one_egg","cracked_state"="no_cracks"]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["turtle_egg_count"="three_egg","cracked_state"="cracks"] run setblock ${x} ${y} ${z} ${blockId} ["turtle_egg_count"="one_egg","cracked_state"="cracks"]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["turtle_egg_count"="three_egg","cracked_state"="max_cracks"] run setblock ${x} ${y} ${z} ${blockId} ["turtle_egg_count"="one_egg","cracked_state"="max_cracks"]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["turtle_egg_count"="four_egg","cracked_state"="no_cracks"] run setblock ${x} ${y} ${z} ${blockId} ["turtle_egg_count"="one_egg","cracked_state"="no_cracks"]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["turtle_egg_count"="four_egg","cracked_state"="cracks"] run setblock ${x} ${y} ${z} ${blockId} ["turtle_egg_count"="one_egg","cracked_state"="cracks"]`)
    source.runCommand(`execute if block ${x} ${y} ${z} ${blockId} ["turtle_egg_count"="four_egg","cracked_state"="max_cracks"] run setblock ${x} ${y} ${z} ${blockId} ["turtle_egg_count"="one_egg","cracked_state"="max_cracks"]`)
}