export const states_result = {
    "default": {
        "active": [true, false],
        "age_bit": [true, false],
        "age": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
        "allow_underwater_bit": [true, false],
        "attached_bit": [true, false],
        "attachment": ["standing", "hanging", "side", "multiple"],
        "bamboo_leaf_size": ["no_leaves", "small_leaves", "large_leaves"],
        "bamboo_stalk_thickness": ["thin", "thick"],
        "big_dripleaf_head": [true, false],
        "big_dripleaf_tilt": ["none", "unstable", "partial_tilt", "full_tilt"],
        "bite_counter": [0, 1, 2, 3, 4, 5, 6],
        "block_light_level": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
        "bloom": [true, false],
        "books_stored": [0, 1, 2, 3, 4, 5, 6],
        "brewing_stand_slot_a_bit": [true, false],
        "brewing_stand_slot_b_bit": [true, false],
        "brewing_stand_slot_c_bit": [true, false],
        "brushed_progress": [0, 1, 2, 3],
        "button_pressed_bit": [true, false],
        "can_summon": [true, false],
        "candles": [0, 1, 2, 3],
        "cardinal_direction": ["north", "south", "east", "west"],
        "cauldron_liquid": ["water", "lava", "powder_snow"],
        "chemistry_table_type": ["compound_creator", "material_reducer", "element_constructor", "lab_table"],
        "chisel_type": ["default", "chiseled", "lines", "smooth"],
        "cluster_count": [0, 1, 2, 3],
        "color_bit": [true, false],
        "color": ["white", "silver", "gray", "black", "brown", "red", "orange", "yellow", "lime", "green", "cyan", "light_blue", "blue", "purple", "magenta", "pink"],
        "color": ["white", "silver", "gray", "black", "brown", "red", "orange", "yellow", "lime", "green", "cyan", "light_blue", "blue", "purple", "magenta", "pink"],
        "composter_fill_level": [0, 1, 2, 3, 4, 5, 6, 7, 8],
        "conditional_bit": [true, false],
        "coral_color": ["blue", "pink", "purple", "red", "yellow"],
        "coral_direction": [0, 1, 2, 3],
        "coral_fan_direction": [0, 1],
        "coral_hang_type_bit": [true, false],
        "covered_bit": [true, false],
        "cracked_state": ["no_cracks", "cracked", "max_cracked"],
        "crafting": [true, false],
        "creaking_heart_state": ["uprooted", "dormant", "awake"],
        "damage": ["undamaged", "slightly_damaged", "very_damaged", "broken"],
        "dead_bit": [true, false],
        "deprecated": [0, 1, 2, 3],
        "direction": [0, 1, 2, 3],
        "dirt_type": ["normal", "coarse"],
        "disarmed_bit": [true, false],
        "door_hinge_bit": [true, false],
        "double_plant_type": ["sunflower", "syringa", "rose", "paeonia", "grass", "fern",],
        "drag_down": [true, false],
        "dripstone_thickness": ["tip", "merge", "frustum", "middle", "base"],
        "end_portal_eye_bit": [true, false],
        "explode_bit": [true, false],
        "extinguished": [true, false],
        "facing_direction": [0, 1, 2, 3, 4, 5],
        "fill_level": [0, 1, 2, 3, 4, 5, 6],
        "flower_type": ["poppy", "orchid", "allium", "houstonia", "tulip_red", "tulip_orange", "tulip_white", "tulip_pink", "oxeye", "cornflower", "lily_of_the_valley"],
        "ground_sign_direction": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
        "growth": [0, 1, 2, 3, 4, 5, 6, 7],
        "hanging": [true, false],
        "head_piece_bit": [true, false],
        "height": [0, 1, 2, 3, 4, 5, 6, 7],
        "honey_level": [0, 1, 2, 3, 4, 5],
        "huge_mushroom_bits": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
        "in_wall_bit": [true, false],
        "infiniburn_bit": [true, false],
        "item_frame_map_bit": [true, false],
        "item_frame_photo_bit": [true, false],
        "kelp_age": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
        "lever_direction": ["up_east_west", "up_north_south", "west", "east", "north", "south", "down_east_west", "down_north_south"],
        "liquid_depth": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
        "lit": [true, false],
        "minecraft:block_face": ["down", "up", "north", "south", "east", "west"],
        "minecraft:cardinal_direction": ["north", "south", "east", "west"],
        "minecraft:connection_east": [true, false],
        "minecraft:connection_north": [true, false],
        "minecraft:connection_south": [true, false],
        "minecraft:connection_west": [true, false],
        "minecraft:corner": ["inner_left", "inner_right", "outer_left", "outer_right", "none"],
        "minecraft:facing_direction": ["down", "up", "north", "south", "east", "west"],
        "minecraft:multi_block_part": [0, 1, 2, 3],
        "minecraft:vertical_half": ["bottom", "top"],
        "moisturized_amount": [0, 1, 2, 3, 4, 5, 6, 7],
        "monster_egg_stone_type": ["stone", "cobblestone", "stone_brick", "mossy_stone_brick", "cracked_stone_brick", "chiseled_stone_brick"],
        "multi_face_direction_bits": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63],
        "natural": [true, false],
        "new_leaf_type": ["acacia", "dark_oak"],
        "new_log_type": ["acacia", "dark_oak"],
        "no_drop_bit": [true, false],
        "nodrop_bit": [true, false],
        "occupied_bit": [true, false],
        "old_leaf_type": ["oak", "spruce", "birch", "jungle"],
        "old_log_type": ["oak", "spruce", "birch", "jungle"],
        "ominous": [true, false],
        "open_bit": [true, false],
        "orientation": ["west_up", "east_up", "north_up", "south_up", "up_west", "up_east", "up_north", "up_south", "down_west", "down_east", "down_north", "down_south"],
        "output_lit_bit": [true, false],
        "output_subtract_bit": [true, false],
        "pale_moss_carpet_side_east": ["none", "short", "tall"],
        "pale_moss_carpet_side_north": ["none", "short", "tall"],
        "pale_moss_carpet_side_south": ["none", "short", "tall"],
        "pale_moss_carpet_side_west": ["none", "short", "tall"],
        "persistent_bit": [true, false],
        "pillar_axis": ["x", "y", "z"],
        "powered_bit": [true, false],
        "powered_shelf_type": [0, 1, 2, 3],
        "prismarine_block_type": ["default", "brick", "dark"],
        "propagule_stage": [0, 1, 2, 3, 4],
        "rail_data_bit": [true, false],
        "rail_direction": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        "redstone_signal": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
        "rehydration_level": [0, 1, 2, 3],
        "repeater_delay": [0, 1, 2, 3],
        "respawn_anchor_charge": [0, 1, 2, 3, 4],
        "rotation": [0, 1, 2, 3],
        "sand_stone_type": ["default", "heiroglyphs", "cut", "smooth"],
        "sand_type": ["normal", "red"],
        "sapling_type": ["oak", "spling_type", "birch", "jungle", "acacia", "dark_oak"],
        "sculk_sensor_phase": [0, 1, 2],
        "sea_grass_type": ["default", "double_bot", "double_top"],
        "shelf_connection_type": ["unconnected", "right", "center", "left"],
        "sponge_type": ["dry", "wet"],
        "stability_check": [true, false],
        "stability": [0, 1, 2, 3, 4, 5, 6, 7],
        "stone_brick_type": ["default", "mossy", "cracked", "chiseled", "smooth"],
        "stone_slab_type_2": ["red_sandstone", "purpur", "prismarine_rough", "prismarine_dark", "prismarine_brick", "mossy_cobblestone", "smooth_sandstone", "red_nether_brick"],
        "stone_slab_type_3": ["end_stone_brick", "smooth_red_sandstone", "polishe_andesite", "andesite", "diorite", "polished_diorite", "granite", "polished_granite"],
        "stone_slab_type_4": ["mossy_stone_brick", "smooth_quartz", "stone", "cut_sandstone", "cut_red_sandstone"],
        "stone_slab_type": ["smooth_stone", "sandstone", "wood", "cobblestone", "brick", "stone_brick", "quartz", "nether_brick"],
        "stone_type": ["stone", "granite", "granite_smooth", "diorite", "diorite_smooth", "andesite", "andesite_smooth"],
        "stripped_bit": [true, false],
        "structure_block_type": ["data", "save", "load", "corner", "invalid", "export"],
        "structure_void_type": ["void", "air"],
        "suspended_bit": [true, false],
        "tall_grass_type": ["default", "fern"],
        "tip": [true, false],
        "toggle_bit": [true, false],
        "top_slot_bit": [true, false],
        "torch_facing_direction": ["west", "east", "north", "south", "top"],
        "trial_spawner_state": [0, 1, 2, 3, 4, 5],
        "triggered_bit": [true, false],
        "turtle_egg_count": ["one_egg", "two_egg", "three_egg", "four_egg"],
        "twisting_vines_age": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
        "update_bit": [true, false],
        "upper_block_bit": [true, false],
        "upside_down_bit": [true, false],
        "vault_state": ["inactive", "active", "unlocking", "ejecting"],
        "vine_direction_bits": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
        "wall_block_type": ["cobblestone", "mossy_cobblestone", "granite", "diorite", "andesite", "sandstone", "brick", "stone_brick", "mossy_stone_brick", "nether_brick", "end_brick", "prismarine", "red_sandstone", "red_nether_brick"],
        "wall_connection_type_east": ["none", "short", "tall"],
        "wall_connection_type_north": ["none", "short", "tall"],
        "wall_connection_type_south": ["none", "short", "tall"],
        "wall_connection_type_west": ["none", "short", "tall"],
        "wall_post_bit": [true, false],
        "weeping_vines_age": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
        "weirdo_direction": [0, 1, 2, 3],
        "wood_type": ["oak", "spruce", "birch", "jungle", "acacia", "dark_oak"],
        "y_rotation_offset": [0.0, 90.0, 180.0, 270.0],
    },
    "blocks": {
        // 向き指定
        "minecraft:chest": { "facing_direction": [2, 3, 4, 5], },
        "minecraft:trapped_chest": { "facing_direction": [2, 3, 4, 5], },
        "minecraft:ender_chest": { "facing_direction": [2, 3, 4, 5], },
        "minecraft:furnace": { "facing_direction": [2, 3, 4, 5], },
        "minecraft:blast_furnace": { "facing_direction": [2, 3, 4, 5], },
        "minecraft:smoker": { "facing_direction": [2, 3, 4, 5], },
        "minecraft:ladder": { "facing_direction": [2, 3, 4, 5], },
        "minecraft:wall_banner": { "facing_direction": [2, 3, 4, 5], },
        "minecraft:wall_sign": { "facing_direction": [2, 3, 4, 5], },
        "minecraft:spruce_wall_sign": { "facing_direction": [2, 3, 4, 5], },
        "minecraft:birch_wall_sign": { "facing_direction": [2, 3, 4, 5], },
        "minecraft:jungle_wall_sign": { "facing_direction": [2, 3, 4, 5], },
        "minecraft:acacia_wall_sign": { "facing_direction": [2, 3, 4, 5], },
        "minecraft:darkoak_wall_sign": { "facing_direction": [2, 3, 4, 5], },
        "minecraft:mangrove_wall_sign": { "facing_direction": [2, 3, 4, 5], },
        "minecraft:cherry_wall_sign": { "facing_direction": [2, 3, 4, 5], },
        "minecraft:bamboo_wall_sign": { "facing_direction": [2, 3, 4, 5], },
        "minecraft:crimson_wall_sign": { "facing_direction": [2, 3, 4, 5], },
        "minecraft:warped_wall_sign": { "facing_direction": [2, 3, 4, 5], },
        // レール系
        "minecraft:golden_rail": { "rail_direction": [0, 1, 2, 3, 4, 5] },
        "minecraft:detector_rail": { "rail_direction": [0, 1, 2, 3, 4, 5] },
        "minecraft:activator_rail": { "rail_direction": [0, 1, 2, 3, 4, 5] },
        // 成長段階
        "minecraft:cocoa": { "age": [0, 1, 2] },
        "minecraft:nether_wart": { "age": [0, 1, 2, 3] },
        "minecraft:chorus_flower": { "age": [0, 1, 2, 3, 4, 5] },
        "minecraft:pink_petals": { "growth": [0, 1, 2, 3] },
        "minecraft:wildflowers": { "growth": [0, 1, 2, 3] },
        "minecraft:leaf_litter": { "growth": [0, 1, 2, 3] },
    }
}