export const states_result_default = {
    // bool値
    "upside_down_bit": [true, false],
    "open_bit": [true, false],
    "triggered_bit": [true, false],
    "powered_bit": [true, false],
    "output_subtract_bit": [true, false],
    "toggle_bit": [true, false],
    "in_wall_bit": [true, false],
    "dead_bit": [true, false],
    "attached_bit": [true, false],
    "rail_data_bit": [true, false],
    "button_pressed_bit": [true, false],
    "allow_underwater_bit": [true, false],
    "explode_bit": [true, false],
    "item_frame_map_bit": [true, false],
    "item_frame_photo_bit": [true, false],
    "covered_bit": [true, false],
    "end_portal_eye_bit": [true, false],
    "age_bit": [true, false],
    "persistent_bit": [true, false],
    "update_bit": [true, false],
    "upper_block_bit": [true, false],
    "coral_hang_type_bit": [true, false],
    "occupied_bit": [true, false],
    "infiniburn_bit": [true, false],
    "wall_post_bit": [true, false],
    "brewing_stand_slot_a_bit": [true, false],
    "brewing_stand_slot_b_bit": [true, false],
    "brewing_stand_slot_c_bit": [true, false],
    "drag_down": [true, false],
    "conditional_bit": [true, false],
    "door_hinge_bit": [true, false],
    "nodrop_bit": [true, false],
    "top_slot_bit": [true, false],
    "output_lit_bit": [true, false],
    "extinguished": [true, false],
    "lit": [true, false],
    "stability_check": [true, false],
    "ominous": [true, false],
    "disarmed_bit": [true, false],
    "suspended_bit": [true, false],
    "stripped_bit": [true, false],
    "crafting": [true, false],
    "hanging": [true, false],
    "can_summon": [true, false],
    "active": [true, false],
    "bloom": [true, false],
    "big_dripleaf_head": [true, false],
    "tip": [true, false],
    "natural": [true, false],
    "color_bit": [true, false],
    "head_piece_bit": [true, false],
    // 数字
    "sculk_sensor_phase": [0, 1, 2],
    "direction": [0, 1, 2, 3],
    "weirdo_direction": [0, 1, 2, 3],
    "coral_direction": [0, 1, 2, 3],
    "cluster_count": [0, 1, 2, 3],
    "candles": [0, 1, 2, 3],
    "rotation": [0, 1, 2, 3],
    "repeater_delay": [0, 1, 2, 3],
    "deprecated": [0, 1, 2, 3],
    "brushed_progress": [0, 1, 2, 3],
    "rehydration_level": [0, 1, 2, 3],
    "powered_shelf_type": [0, 1, 2, 3],
    "propagule_stage": [0, 1, 2, 3, 4],
    "respawn_anchor_charge": [0, 1, 2, 3, 4],
    "honey_level": [0, 1, 2, 3, 4, 5],
    "facing_direction": [0, 1, 2, 3, 4, 5],
    "trial_spawner_state": [0, 1, 2, 3, 4, 5],
    "fill_level": [0, 1, 2, 3, 4, 5, 6],
    "growth": [0, 1, 2, 3, 4, 5, 6, 7],
    "height": [0, 1, 2, 3, 4, 5, 6, 7],
    "stability": [0, 1, 2, 3, 4, 5, 6, 7],
    "moisturized_amount": [0, 1, 2, 3, 4, 5, 6, 7],
    "composter_fill_level": [0, 1, 2, 3, 4, 5, 6, 7, 8],
    "rail_direction": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    "age": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    "redstone_signal": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    "huge_mushroom_bits": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    "ground_sign_direction": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    "weeping_vines_age": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
    "twisting_vines_age": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
    "kelp_age": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
    "books_stored": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63],
    "multi_face_direction_bits": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63],
    "bite_counter": [0, 1, 2, 3, 4, 5, 6],
    "liquid_depth": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    "vine_direction_bits": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    // 文字列
    "wall_connection_type_east": ["none", "short", "tall"],
    "wall_connection_type_north": ["none", "short", "tall"],
    "wall_connection_type_south": ["none", "short", "tall"],
    "wall_connection_type_west": ["none", "short", "tall"],
    "pale_moss_carpet_side_east": ["none", "short", "tall"],
    "pale_moss_carpet_side_north": ["none", "short", "tall"],
    "pale_moss_carpet_side_south": ["none", "short", "tall"],
    "pale_moss_carpet_side_west": ["none", "short", "tall"],
    "sponge_type": ["dry", "wet"],
    "structure_block_type": ["data", "save", "load", "corner", "invalid", "export"],
    "chemistry_table_type": ["compound_creator", "material_reducer", "element_constructor", "lab_table"],
    "chisel_type": ["default", "chiseled", "lines", "smooth"],
    "double_plant_type": ["sunflower", "syringa", "rose", "paeonia", "grass", "fern",],
    "flower_type": ["poppy", "orchid", "allium", "houstonia", "tulip_red", "tulip_orange", "tulip_white", "tulip_pink", "oxeye", "cornflower", "lily_of_the_valley"],
    "monster_egg_stone_type": ["stone", "cobblestone", "stone_brick", "mossy_stone_brick", "cracked_stone_brick", "chiseled_stone_brick"],
    "dirt_type": ["normal", "coarse"],
    "sand_type": ["normal", "red"],
    "sand_stone_type": ["default", "heiroglyphs", "cut", "smooth"],
    "wood_type": ["oak", "spruce", "birch", "jungle", "acacia", "dark_oak"],
    "sapling_type": ["oak", "spling_type", "birch", "jungle", "acacia", "dark_oak"],
    "old_log_type": ["oak", "spruce", "birch", "jungle"],
    "new_log_type": ["acacia", "dark_oak"],
    "old_leaf_type": ["oak", "spruce", "birch", "jungle"],
    "new_leaf_type": ["acacia", "dark_oak"],
    "stone_type": ["stone", "granite", "granite_smooth", "diorite", "diorite_smooth", "andesite", "andesite_smooth"],
    "stone_brick_type": ["default", "mossy", "cracked", "chiseled", "smooth"],
    "stone_slab_type": ["smooth_stone", "sandstone", "wood", "cobblestone", "brick", "stone_brick", "quartz", "nether_brick"],
    "stone_slab_type_2": ["red_sandstone", "purpur", "prismarine_rough", "prismarine_dark", "prismarine_brick", "mossy_cobblestone", "smooth_sandstone", "red_nether_brick"],
    "stone_slab_type_3": ["end_stone_brick", "smooth_red_sandstone", "polishe_andesite", "andesite", "diorite", "polished_diorite", "granite", "polished_granite"],
    "stone_slab_type_4": ["mossy_stone_brick", "smooth_quartz", "stone", "cut_sandstone", "cut_red_sandstone"],
    "wall_block_type": ["cobblestone", "mossy_cobblestone", "granite", "diorite", "andesite", "sandstone", "brick", "stone_brick", "mossy_stone_brick", "nether_brick", "end_brick", "prismarine", "red_sandstone", "red_nether_brick"],
    "prismarine_block_type": ["default", "brick", "dark"],
    "tall_grass_type": ["default", "fern",],
    "structure_void_type": ["void", "air"],
    "sea_grass_type": ["default", "double_bot", "double_top"],
    "pillar_axis": ["x", "y", "z"],
    "bamboo_stalk_thickness": ["thin", "thick"],
    "cauldron_liquid": ["water", "lava", "powder_snow"],
    "bamboo_leaf_size": ["no_leaves", "small_leaves", "large_leaves"],
    "attachment": ["standing", "hanging", "side", "multiple"],
    "damage": ["undamaged", "slightly_damaged", "very_damaged"],
    "dripstone_thickness": ["tip", "merge", "frustum", "middle", "base"],
    "big_dripleaf_tilt": ["none", "unstable", "partial_tilt", "full_tilt"],
    "vault_state": ["inactive", "active", "unlocking", "ejecting "],
    "torch_facing_direction": ["west", "east", "north", "south", "top"],
    "lever_direction": ["up_east_west", "up_north_south", "west", "east", "north", "south", "down_east_west", "down_north_south"],
    "orientation": ["west_up", "east_up", "north_up", "south_up", "up_west", "up_east", "up_north", "up_south", "down_west", "down_east", "down_north", "down_south"],
    "color": ["white", "silver", "gray", "black", "brown", "red", "orange", "yellow", "lime", "green", "cyan", "light_blue", "blue", "purple", "magenta", "pink"],
    "coral_color": ["blue", "pink", "purple", "red", "yellow"],
    "cracked_state": ["no_cracks", "cracked", "max_cracked"],
    "portal_axis": ["unknown", "x", "z"],
    "turtle_egg_count": ["one_egg", "two_egg", "three_egg", "four_egg"],
    // "minecraft:placement_direction"
    "minecraft:cardinal_direction": ["north", "south", "east", "west"],
    "minecraft:facing_direction": ["down", "up", "north", "south", "east", "west"],
    "y_rotation_offset": [0.0, 90.0, 180.0, 270.0],
    // "minecraft:placement_position"
    "minecraft:block_face": ["down", "up", "north", "south", "east", "west"],
    "minecraft:vertical_half": ["bottom", "top"],
}