export const Block_id_json = {
    "ID": {
        // 階段
        "minecraft:normal_stone_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:stone_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:mossy_cobblestone_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:oak_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:spruce_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:birch_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:jungle_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:acacia_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:dark_oak_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:mangrove_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:cherry_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:bamboo_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:bamboo_mosaic_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:stone_brick_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:mossy_stone_brick_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:sandstone_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:smooth_sandstone_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:red_sandstone_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:smooth_red_sandstone_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:granite_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:polished_granite_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:diorite_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:polished_diorite_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:andesite_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:polished_andesite_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:brick_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:nether_brick_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:red_nether_brick_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:end_brick_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:quartz_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:smooth_quartz_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:purpur_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:prismarine_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:dark_prismarine_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:prismarine_bricks_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:crimson_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:warped_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:blackstone_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:polished_blackstone_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:polished_blackstone_brick_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:cobbled_deepslate_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:deepslate_tile_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:polished_deepslate_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:deepslate_brick_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:tuff_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:polished_tuff_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:tuff_brick_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:mud_brick_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:cut_copper_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:exposed_cut_copper_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:weathered_cut_copper_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:oxidized_cut_copper_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:waxed_cut_copper_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:waxed_exposed_cut_copper_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:waxed_weathered_cut_copper_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:waxed_oxidized_cut_copper_stairs": ["weirdo_direction", "upside_down_bit"],
        // ハーフブロック
        "minecraft:smooth_stone_slab": ["minecraft:vertical_half"],
        "minecraft:normal_stone_slab": ["minecraft:vertical_half"],
        "minecraft:cobblestone_slab": ["minecraft:vertical_half"],
        "minecraft:mossy_cobblestone_slab": ["minecraft:vertical_half"],
        "minecraft:oak_slab": ["minecraft:vertical_half"],
        "minecraft:spruce_slab": ["minecraft:vertical_half"],
        "minecraft:birch_slab": ["minecraft:vertical_half"],
        "minecraft:jungle_slab": ["minecraft:vertical_half"],
        "minecraft:acacia_slab": ["minecraft:vertical_half"],
        "minecraft:dark_oak_slab": ["minecraft:vertical_half"],
        "minecraft:mangrove_slab": ["minecraft:vertical_half"],
        "minecraft:cherry_slab": ["minecraft:vertical_half"],
        "minecraft:bamboo_slab": ["minecraft:vertical_half"],
        "minecraft:bamboo_mosaic_slab": ["minecraft:vertical_half"],
        "minecraft:stone_brick_slab": ["minecraft:vertical_half"],
        "minecraft:mossy_stone_brick_slab": ["minecraft:vertical_half"],
        "minecraft:sandstone_slab": ["minecraft:vertical_half"],
        "minecraft:cut_sandstone_slab": ["minecraft:vertical_half"],
        "minecraft:smooth_sandstone_slab": ["minecraft:vertical_half"],
        "minecraft:red_sandstone_slab": ["minecraft:vertical_half"],
        "minecraft:cut_red_sandstone_slab": ["minecraft:vertical_half"],
        "minecraft:smooth_red_sandstone_slab": ["minecraft:vertical_half"],
        "minecraft:granite_slab": ["minecraft:vertical_half"],
        "minecraft:polished_granite_slab": ["minecraft:vertical_half"],
        "minecraft:diorite_slab": ["minecraft:vertical_half"],
        "minecraft:polished_diorite_slab": ["minecraft:vertical_half"],
        "minecraft:andesite_slab": ["minecraft:vertical_half"],
        "minecraft:polished_andesite_slab": ["minecraft:vertical_half"],
        "minecraft:brick_slab": ["minecraft:vertical_half"],
        "minecraft:nether_brick_slab": ["minecraft:vertical_half"],
        "minecraft:red_nether_brick_slab": ["minecraft:vertical_half"],
        "minecraft:end_stone_brick_slab": ["minecraft:vertical_half"],
        "minecraft:quartz_slab": ["minecraft:vertical_half"],
        "minecraft:smooth_quartz_slab": ["minecraft:vertical_half"],
        "minecraft:purpur_slab": ["minecraft:vertical_half"],
        "minecraft:prismarine_slab": ["minecraft:vertical_half"],
        "minecraft:dark_prismarine_slab": ["minecraft:vertical_half"],
        "minecraft:prismarine_brick_slab": ["minecraft:vertical_half"],
        "minecraft:crimson_slab": ["minecraft:vertical_half"],
        "minecraft:warped_slab": ["minecraft:vertical_half"],
        "minecraft:blackstone_slab": ["minecraft:vertical_half"],
        "minecraft:polished_blackstone_slab": ["minecraft:vertical_half"],
        "minecraft:polished_blackstone_brick_slab": ["minecraft:vertical_half"],
        "minecraft:cobbled_deepslate_slab": ["minecraft:vertical_half"],
        "minecraft:deepslate_tile_slab": ["minecraft:vertical_half"],
        "minecraft:polished_deepslate_slab": ["minecraft:vertical_half"],
        "minecraft:deepslate_brick_slab": ["minecraft:vertical_half"],
        "minecraft:tuff_slab": ["minecraft:vertical_half"],
        "minecraft:polished_tuff_slab": ["minecraft:vertical_half"],
        "minecraft:tuff_brick_slab": ["minecraft:vertical_half"],
        "minecraft:mud_brick_slab": ["minecraft:vertical_half"],
        "minecraft:cut_copper_slab": ["minecraft:vertical_half"],
        "minecraft:exposed_cut_copper_slab": ["minecraft:vertical_half"],
        "minecraft:weathered_cut_copper_slab": ["minecraft:vertical_half"],
        "minecraft:oxidized_cut_copper_slab": ["minecraft:vertical_half"],
        "minecraft:waxed_cut_copper_slab": ["minecraft:vertical_half"],
        "minecraft:waxed_exposed_cut_copper_slab": ["minecraft:vertical_half"],
        "minecraft:waxed_weathered_cut_copper_slab": ["minecraft:vertical_half"],
        "minecraft:waxed_oxidized_cut_copper_slab": ["minecraft:vertical_half"],
        // ハーフブロック_double
        "minecraft:smooth_stone_double_slab": ["minecraft:vertical_half"],
        "minecraft:normal_stone_double_slab": ["minecraft:vertical_half"],
        "minecraft:cobblestone_double_slab": ["minecraft:vertical_half"],
        "minecraft:mossy_cobblestone_double_slab": ["minecraft:vertical_half"],
        "minecraft:oak_double_slab": ["minecraft:vertical_half"],
        "minecraft:spruce_double_slab": ["minecraft:vertical_half"],
        "minecraft:birch_double_slab": ["minecraft:vertical_half"],
        "minecraft:jungle_double_slab": ["minecraft:vertical_half"],
        "minecraft:acacia_double_slab": ["minecraft:vertical_half"],
        "minecraft:dark_oak_double_slab": ["minecraft:vertical_half"],
        "minecraft:mangrove_double_slab": ["minecraft:vertical_half"],
        "minecraft:cherry_double_slab": ["minecraft:vertical_half"],
        "minecraft:bamboo_double_slab": ["minecraft:vertical_half"],
        "minecraft:bamboo_mosaic_double_slab": ["minecraft:vertical_half"],
        "minecraft:stone_brick_double_slab": ["minecraft:vertical_half"],
        "minecraft:mossy_stone_brick_double_slab": ["minecraft:vertical_half"],
        "minecraft:sandstone_double_slab": ["minecraft:vertical_half"],
        "minecraft:cut_sandstone_double_slab": ["minecraft:vertical_half"],
        "minecraft:smooth_sandstone_double_slab": ["minecraft:vertical_half"],
        "minecraft:red_sandstone_double_slab": ["minecraft:vertical_half"],
        "minecraft:cut_red_sandstone_double_slab": ["minecraft:vertical_half"],
        "minecraft:smooth_red_sandstone_double_slab": ["minecraft:vertical_half"],
        "minecraft:granite_double_slab": ["minecraft:vertical_half"],
        "minecraft:polished_granite_double_slab": ["minecraft:vertical_half"],
        "minecraft:diorite_double_slab": ["minecraft:vertical_half"],
        "minecraft:polished_diorite_double_slab": ["minecraft:vertical_half"],
        "minecraft:andesite_double_slab": ["minecraft:vertical_half"],
        "minecraft:polished_andesite_double_slab": ["minecraft:vertical_half"],
        "minecraft:brick_double_slab": ["minecraft:vertical_half"],
        "minecraft:nether_brick_double_slab": ["minecraft:vertical_half"],
        "minecraft:red_nether_brick_double_slab": ["minecraft:vertical_half"],
        "minecraft:end_stone_brick_double_slab": ["minecraft:vertical_half"],
        "minecraft:quartz_double_slab": ["minecraft:vertical_half"],
        "minecraft:smooth_quartz_double_slab": ["minecraft:vertical_half"],
        "minecraft:purpur_double_slab": ["minecraft:vertical_half"],
        "minecraft:prismarine_double_slab": ["minecraft:vertical_half"],
        "minecraft:dark_prismarine_double_slab": ["minecraft:vertical_half"],
        "minecraft:prismarine_brick_double_slab": ["minecraft:vertical_half"],
        "minecraft:crimson_double_slab": ["minecraft:vertical_half"],
        "minecraft:warped_double_slab": ["minecraft:vertical_half"],
        "minecraft:blackstone_double_slab": ["minecraft:vertical_half"],
        "minecraft:polished_blackstone_double_slab": ["minecraft:vertical_half"],
        "minecraft:polished_blackstone_brick_double_slab": ["minecraft:vertical_half"],
        "minecraft:cobbled_deepslate_double_slab": ["minecraft:vertical_half"],
        "minecraft:deepslate_tile_double_slab": ["minecraft:vertical_half"],
        "minecraft:polished_deepslate_double_slab": ["minecraft:vertical_half"],
        "minecraft:deepslate_brick_double_slab": ["minecraft:vertical_half"],
        "minecraft:tuff_double_slab": ["minecraft:vertical_half"],
        "minecraft:polished_tuff_double_slab": ["minecraft:vertical_half"],
        "minecraft:tuff_brick_double_slab": ["minecraft:vertical_half"],
        "minecraft:mud_brick_double_slab": ["minecraft:vertical_half"],

        "minecraft:double_cut_copper_slab": ["minecraft:vertical_half"],
        "minecraft:exposed_double_cut_copper_slab": ["minecraft:vertical_half"],
        "minecraft:weathered_double_cut_copper_slab": ["minecraft:vertical_half"],
        "minecraft:oxidized_double_cut_copper_slab": ["minecraft:vertical_half"],
        "minecraft:waxed_double_cut_copper_slab": ["minecraft:vertical_half"],
        "minecraft:waxed_exposed_double_cut_copper_slab": ["minecraft:vertical_half"],
        "minecraft:waxed_weathered_double_cut_copper_slab": ["minecraft:vertical_half"],
        "minecraft:waxed_oxidized_double_cut_copper_slab": ["minecraft:vertical_half"],
    }
}