export const Block_id_json = {
    "ID": {
        // 階段
        "minecraft:normal_stone_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:stone_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:mossy_cobblestone_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:oak_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:spruce_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:birch_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:jungle_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:acacia_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:dark_oak_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:mangrove_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:cherry_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:bamboo_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:bamboo_mosaic_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:stone_brick_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:mossy_stone_brick_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:sandstone_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:smooth_sandstone_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:red_sandstone_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:smooth_red_sandstone_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:granite_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:polished_granite_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:diorite_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:polished_diorite_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:andesite_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:polished_andesite_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:brick_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:nether_brick_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:red_nether_brick_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:end_brick_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:quartz_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:smooth_quartz_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:purpur_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:prismarine_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:dark_prismarine_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:prismarine_bricks_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:crimson_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:warped_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:blackstone_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:polished_blackstone_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:polished_blackstone_brick_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:cobbled_deepslate_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:deepslate_tile_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:polished_deepslate_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:deepslate_brick_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:tuff_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:polished_tuff_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:tuff_brick_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:mud_brick_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:cut_copper_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:exposed_cut_copper_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:weathered_cut_copper_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:oxidized_cut_copper_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:waxed_cut_copper_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:waxed_exposed_cut_copper_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:waxed_weathered_cut_copper_stairs": ["weirdo_direction", "upside_down_bit"],
        "minecraft:waxed_oxidized_cut_copper_stairs": ["weirdo_direction", "upside_down_bit"],
        // ハーフブロック
        "minecraft:smooth_stone_slab": ["minecraft:vertical_half"],
        "minecraft:normal_stone_slab": ["minecraft:vertical_half"],
        "minecraft:cobblestone_slab": ["minecraft:vertical_half"],
        "minecraft:mossy_cobblestone_slab": ["minecraft:vertical_half"],
        "minecraft:oak_slab": ["minecraft:vertical_half"],
        "minecraft:spruce_slab": ["minecraft:vertical_half"],
        "minecraft:birch_slab": ["minecraft:vertical_half"],
        "minecraft:jungle_slab": ["minecraft:vertical_half"],
        "minecraft:acacia_slab": ["minecraft:vertical_half"],
        "minecraft:dark_oak_slab": ["minecraft:vertical_half"],
        "minecraft:mangrove_slab": ["minecraft:vertical_half"],
        "minecraft:cherry_slab": ["minecraft:vertical_half"],
        "minecraft:bamboo_slab": ["minecraft:vertical_half"],
        "minecraft:bamboo_mosaic_slab": ["minecraft:vertical_half"],
        "minecraft:stone_brick_slab": ["minecraft:vertical_half"],
        "minecraft:mossy_stone_brick_slab": ["minecraft:vertical_half"],
        "minecraft:sandstone_slab": ["minecraft:vertical_half"],
        "minecraft:cut_sandstone_slab": ["minecraft:vertical_half"],
        "minecraft:smooth_sandstone_slab": ["minecraft:vertical_half"],
        "minecraft:red_sandstone_slab": ["minecraft:vertical_half"],
        "minecraft:cut_red_sandstone_slab": ["minecraft:vertical_half"],
        "minecraft:smooth_red_sandstone_slab": ["minecraft:vertical_half"],
        "minecraft:granite_slab": ["minecraft:vertical_half"],
        "minecraft:polished_granite_slab": ["minecraft:vertical_half"],
        "minecraft:diorite_slab": ["minecraft:vertical_half"],
        "minecraft:polished_diorite_slab": ["minecraft:vertical_half"],
        "minecraft:andesite_slab": ["minecraft:vertical_half"],
        "minecraft:polished_andesite_slab": ["minecraft:vertical_half"],
        "minecraft:brick_slab": ["minecraft:vertical_half"],
        "minecraft:nether_brick_slab": ["minecraft:vertical_half"],
        "minecraft:red_nether_brick_slab": ["minecraft:vertical_half"],
        "minecraft:end_stone_brick_slab": ["minecraft:vertical_half"],
        "minecraft:quartz_slab": ["minecraft:vertical_half"],
        "minecraft:smooth_quartz_slab": ["minecraft:vertical_half"],
        "minecraft:purpur_slab": ["minecraft:vertical_half"],
        "minecraft:prismarine_slab": ["minecraft:vertical_half"],
        "minecraft:dark_prismarine_slab": ["minecraft:vertical_half"],
        "minecraft:prismarine_brick_slab": ["minecraft:vertical_half"],
        "minecraft:crimson_slab": ["minecraft:vertical_half"],
        "minecraft:warped_slab": ["minecraft:vertical_half"],
        "minecraft:blackstone_slab": ["minecraft:vertical_half"],
        "minecraft:polished_blackstone_slab": ["minecraft:vertical_half"],
        "minecraft:polished_blackstone_brick_slab": ["minecraft:vertical_half"],
        "minecraft:cobbled_deepslate_slab": ["minecraft:vertical_half"],
        "minecraft:deepslate_tile_slab": ["minecraft:vertical_half"],
        "minecraft:polished_deepslate_slab": ["minecraft:vertical_half"],
        "minecraft:deepslate_brick_slab": ["minecraft:vertical_half"],
        "minecraft:tuff_slab": ["minecraft:vertical_half"],
        "minecraft:polished_tuff_slab": ["minecraft:vertical_half"],
        "minecraft:tuff_brick_slab": ["minecraft:vertical_half"],
        "minecraft:mud_brick_slab": ["minecraft:vertical_half"],
        "minecraft:cut_copper_slab": ["minecraft:vertical_half"],
        "minecraft:exposed_cut_copper_slab": ["minecraft:vertical_half"],
        "minecraft:weathered_cut_copper_slab": ["minecraft:vertical_half"],
        "minecraft:oxidized_cut_copper_slab": ["minecraft:vertical_half"],
        "minecraft:waxed_cut_copper_slab": ["minecraft:vertical_half"],
        "minecraft:waxed_exposed_cut_copper_slab": ["minecraft:vertical_half"],
        "minecraft:waxed_weathered_cut_copper_slab": ["minecraft:vertical_half"],
        "minecraft:waxed_oxidized_cut_copper_slab": ["minecraft:vertical_half"],
        // トラップドア
        "minecraft:trapdoor": ["direction", "open_bit", "upside_down_bit"],
        "minecraft:spruce_trapdoor": ["direction", "open_bit", "upside_down_bit"],
        "minecraft:birch_trapdoor": ["direction", "open_bit", "upside_down_bit"],
        "minecraft:jungle_trapdoor": ["direction", "open_bit", "upside_down_bit"],
        "minecraft:acacia_trapdoor": ["direction", "open_bit", "upside_down_bit"],
        "minecraft:dark_oak_trapdoor": ["direction", "open_bit", "upside_down_bit"],
        "minecraft:mangrove_trapdoor": ["direction", "open_bit", "upside_down_bit"],
        "minecraft:cherry_trapdoor": ["direction", "open_bit", "upside_down_bit"],
        "minecraft:bamboo_trapdoor": ["direction", "open_bit", "upside_down_bit"],
        "minecraft:iron_trapdoor": ["direction", "open_bit", "upside_down_bit"],
        "minecraft:crimson_trapdoor": ["direction", "open_bit", "upside_down_bit"],
        "minecraft:warped_trapdoor": ["direction", "open_bit", "upside_down_bit"],
        "minecraft:copper_trapdoor": ["direction", "open_bit", "upside_down_bit"],
        "minecraft:exposed_copper_trapdoor": ["direction", "open_bit", "upside_down_bit"],
        "minecraft:weathered_copper_trapdoor": ["direction", "open_bit", "upside_down_bit"],
        "minecraft:oxidized_copper_trapdoor": ["direction", "open_bit", "upside_down_bit"],
        "minecraft:waxed_copper_trapdoor": ["direction", "open_bit", "upside_down_bit"],
        "minecraft:waxed_exposed_copper_trapdoor": ["direction", "open_bit", "upside_down_bit"],
        "minecraft:waxed_weathered_copper_trapdoor": ["direction", "open_bit", "upside_down_bit"],
        "minecraft:waxed_oxidized_copper_trapdoor": ["direction", "open_bit", "upside_down_bit"],
        // フェンスゲート
        "minecraft:fence_gate": ["direction", "in_wall_bit", "open_bit"],
        "minecraft:spruce_fence_gate": ["direction", "in_wall_bit", "open_bit"],
        "minecraft:birch_fence_gate": ["direction", "in_wall_bit", "open_bit"],
        "minecraft:jungle_fence_gate": ["direction", "in_wall_bit", "open_bit"],
        "minecraft:acacia_fence_gate": ["direction", "in_wall_bit", "open_bit"],
        "minecraft:dark_oak_fence_gate": ["direction", "in_wall_bit", "open_bit"],
        "minecraft:mangrove_fence_gate": ["direction", "in_wall_bit", "open_bit"],
        "minecraft:cherry_fence_gate": ["direction", "in_wall_bit", "open_bit"],
        "minecraft:bamboo_fence_gate": ["direction", "in_wall_bit", "open_bit"],
        "minecraft:crimson_fence_gate": ["direction", "in_wall_bit", "open_bit"],
        "minecraft:warped_fence_gate": ["direction", "in_wall_bit", "open_bit"],
        // 原木
        "minecraft:oak_log": ["pillar_axis"],
        "minecraft:stripped_oak_log": ["pillar_axis"],
        "minecraft:spruce_log": ["pillar_axis"],
        "minecraft:stripped_spruce_log": ["pillar_axis"],
        "minecraft:birch_log": ["pillar_axis"],
        "minecraft:stripped_birch_log": ["pillar_axis"],
        "minecraft:jungle_log": ["pillar_axis"],
        "minecraft:stripped_jungle_log": ["pillar_axis"],
        "minecraft:acacia_log": ["pillar_axis"],
        "minecraft:stripped_acacia_log": ["pillar_axis"],
        "minecraft:dark_oak_log": ["pillar_axis"],
        "minecraft:stripped_dark_oak_log": ["pillar_axis"],
        "minecraft:mangrove_log": ["pillar_axis"],
        "minecraft:stripped_mangrove_log": ["pillar_axis"],
        "minecraft:cherry_log": ["pillar_axis"],
        "minecraft:stripped_cherry_log": ["pillar_axis"],
        "minecraft:crimson_stem": ["pillar_axis"],
        "minecraft:stripped_crimson_stem": ["pillar_axis"],
        "minecraft:warped_stem": ["pillar_axis"],
        "minecraft:stripped_warped_stem": ["pillar_axis"],
        // 木
        "minecraft:oak_wood": ["pillar_axis"],
        "minecraft:stripped_oak_wood": ["pillar_axis"],
        "minecraft:spruce_wood": ["pillar_axis"],
        "minecraft:stripped_spruce_wood": ["pillar_axis"],
        "minecraft:birch_wood": ["pillar_axis"],
        "minecraft:stripped_birch_wood": ["pillar_axis"],
        "minecraft:jungle_wood": ["pillar_axis"],
        "minecraft:stripped_jungle_wood": ["pillar_axis"],
        "minecraft:acacia_wood": ["pillar_axis"],
        "minecraft:stripped_acacia_wood": ["pillar_axis"],
        "minecraft:dark_oak_wood": ["pillar_axis"],
        "minecraft:stripped_dark_oak_wood": ["pillar_axis"],
        "minecraft:mangrove_wood": ["pillar_axis"],
        "minecraft:stripped_mangrove_wood": ["pillar_axis"],
        "minecraft:cherry_wood": ["pillar_axis"],
        "minecraft:stripped_cherry_wood": ["pillar_axis"],
        "minecraft:crimson_hyphae": ["pillar_axis"],
        "minecraft:stripped_crimson_hyphae": ["pillar_axis"],
        "minecraft:warped_hyphae": ["pillar_axis"],
        "minecraft:stripped_warped_hyphae": ["pillar_axis"],
        "minecraft:bamboo_block": ["pillar_axis"],
        "minecraft:stripped_bamboo_block": ["pillar_axis"],
        // 柱
        "minecraft:quartz_pillar": ["pillar_axis"],
        "minecraft:hay_block": ["pillar_axis"],
        "minecraft:bone_block": ["pillar_axis"],
        "minecraft:purpur_pillar": ["pillar_axis"],
        // 彩釉テラコッタ
        "minecraft:white_glazed_terracotta": ["facing_direction"],
        "minecraft:silver_glazed_terracotta": ["facing_direction"],
        "minecraft:gray_glazed_terracotta": ["facing_direction"],
        "minecraft:black_glazed_terracotta": ["facing_direction"],
        "minecraft:brown_glazed_terracotta": ["facing_direction"],
        "minecraft:red_glazed_terracotta": ["facing_direction"],
        "minecraft:orange_glazed_terracotta": ["facing_direction"],
        "minecraft:yellow_glazed_terracotta": ["facing_direction"],
        "minecraft:lime_glazed_terracotta": ["facing_direction"],
        "minecraft:green_glazed_terracotta": ["facing_direction"],
        "minecraft:cyan_glazed_terracotta": ["facing_direction"],
        "minecraft:light_blue_glazed_terracotta": ["facing_direction"],
        "minecraft:blue_glazed_terracotta": ["facing_direction"],
        "minecraft:purple_glazed_terracotta": ["facing_direction"],
        "minecraft:magenta_glazed_terracotta": ["facing_direction"],
        "minecraft:pink_glazed_terracotta": ["facing_direction"],
        // レッドストーン系
        "minecraft:dropper": ["facing_direction", "triggered_bit"],
        "minecraft:dispenser": ["facing_direction", "triggered_bit"],
        "minecraft:crafter": ["triggered_bit", "crafting", "orientation"],
        "minecraft:piston": ["facing_direction"],
        "minecraft:sticky_piston": ["facing_direction"],
        "minecraft:observer": ["minecraft:facing_direction", "powered_bit"],
        "minecraft:unpowered_repeater": ["minecraft:cardinal_direction", "repeater_delay"],
        "minecraft:unpowered_comparator": ["minecraft:cardinal_direction", "output_subtract_bit"],
        "minecraft:hopper": ["toggle_bit", "facing_direction"],
        "minecraft:redstone_wire": ["redstone_signal"],
        // かまど
        "minecraft:furnace": ["minecraft:cardinal_direction"],
        "minecraft:blast_furnace": ["minecraft:cardinal_direction"],
        "minecraft:smoker": ["minecraft:cardinal_direction"],
        // チェスト
        "minecraft:chest": ["minecraft:cardinal_direction"],
        "minecraft:trapped_chest": ["minecraft:cardinal_direction"],
        "minecraft:ender_chest": ["minecraft:cardinal_direction"],
        // ドア
        "minecraft:wooden_door": ["direction", "open_bit"],
        "minecraft:spruce_door": ["direction", "open_bit"],
        "minecraft:birch_door": ["direction", "open_bit"],
        "minecraft:jungle_door": ["direction", "open_bit"],
        "minecraft:acacia_door": ["direction", "open_bit"],
        "minecraft:dark_oak_door": ["direction", "open_bit"],
        "minecraft:mangrove_door": ["direction", "open_bit"],
        "minecraft:cherry_door": ["direction", "open_bit"],
        "minecraft:bamboo_door": ["direction", "open_bit"],
        "minecraft:iron_door": ["direction", "open_bit"],
        "minecraft:crimson_door": ["direction", "open_bit"],
        "minecraft:warped_door": ["direction", "open_bit"],
        "minecraft:copper_door": ["direction", "open_bit"],
        "minecraft:exposed_copper_door": ["direction", "open_bit"],
        "minecraft:weathered_copper_door": ["direction", "open_bit"],
        "minecraft:oxidized_copper_door": ["direction", "open_bit"],
        "minecraft:waxed_copper_door": ["direction", "open_bit"],
        "minecraft:waxed_exposed_copper_door": ["direction", "open_bit"],
        "minecraft:waxed_weathered_copper_door": ["direction", "open_bit"],
        "minecraft:waxed_oxidized_copper_door": ["direction", "open_bit"],
        // 壁
        "minecraft:cobblestone_wall": ["wall_connection_type_east", "wall_connection_type_north", "wall_connection_type_south", "wall_connection_type_west", "wall_post_bit"],
        "minecraft:mossy_cobblestone_wall": ["wall_connection_type_east", "wall_connection_type_north", "wall_connection_type_south", "wall_connection_type_west", "wall_post_bit"],
        "minecraft:granite_wall": ["wall_connection_type_east", "wall_connection_type_north", "wall_connection_type_south", "wall_connection_type_west", "wall_post_bit"],
        "minecraft:diorite_wall": ["wall_connection_type_east", "wall_connection_type_north", "wall_connection_type_south", "wall_connection_type_west", "wall_post_bit"],
        "minecraft:andesite_wall": ["wall_connection_type_east", "wall_connection_type_north", "wall_connection_type_south", "wall_connection_type_west", "wall_post_bit"],
        "minecraft:sandstone_wall": ["wall_connection_type_east", "wall_connection_type_north", "wall_connection_type_south", "wall_connection_type_west", "wall_post_bit"],
        "minecraft:red_sandstone_wall": ["wall_connection_type_east", "wall_connection_type_north", "wall_connection_type_south", "wall_connection_type_west", "wall_post_bit"],
        "minecraft:stone_brick_wall": ["wall_connection_type_east", "wall_connection_type_north", "wall_connection_type_south", "wall_connection_type_west", "wall_post_bit"],
        "minecraft:mossy_stone_brick_wall": ["wall_connection_type_east", "wall_connection_type_north", "wall_connection_type_south", "wall_connection_type_west", "wall_post_bit"],
        "minecraft:brick_wall": ["wall_connection_type_east", "wall_connection_type_north", "wall_connection_type_south", "wall_connection_type_west", "wall_post_bit"],
        "minecraft:nether_brick_wall": ["wall_connection_type_east", "wall_connection_type_north", "wall_connection_type_south", "wall_connection_type_west", "wall_post_bit"],
        "minecraft:red_nether_brick_wall": ["wall_connection_type_east", "wall_connection_type_north", "wall_connection_type_south", "wall_connection_type_west", "wall_post_bit"],
        "minecraft:end_stone_brick_wall": ["wall_connection_type_east", "wall_connection_type_north", "wall_connection_type_south", "wall_connection_type_west", "wall_post_bit"],
        "minecraft:prismarine_wall": ["wall_connection_type_east", "wall_connection_type_north", "wall_connection_type_south", "wall_connection_type_west", "wall_post_bit"],
        "minecraft:blackstone_wall": ["wall_connection_type_east", "wall_connection_type_north", "wall_connection_type_south", "wall_connection_type_west", "wall_post_bit"],
        "minecraft:polished_blackstone_wall": ["wall_connection_type_east", "wall_connection_type_north", "wall_connection_type_south", "wall_connection_type_west", "wall_post_bit"],
        "minecraft:polished_blackstone_brick_wall": ["wall_connection_type_east", "wall_connection_type_north", "wall_connection_type_south", "wall_connection_type_west", "wall_post_bit"],
        "minecraft:cobbled_deepslate_wall": ["wall_connection_type_east", "wall_connection_type_north", "wall_connection_type_south", "wall_connection_type_west", "wall_post_bit"],
        "minecraft:deepslate_tile_wall": ["wall_connection_type_east", "wall_connection_type_north", "wall_connection_type_south", "wall_connection_type_west", "wall_post_bit"],
        "minecraft:polished_deepslate_wall": ["wall_connection_type_east", "wall_connection_type_north", "wall_connection_type_south", "wall_connection_type_west", "wall_post_bit"],
        "minecraft:deepslate_brick_wall": ["wall_connection_type_east", "wall_connection_type_north", "wall_connection_type_south", "wall_connection_type_west", "wall_post_bit"],
        "minecraft:tuff_wall": ["wall_connection_type_east", "wall_connection_type_north", "wall_connection_type_south", "wall_connection_type_west", "wall_post_bit"],
        "minecraft:tuff_brick_wall": ["wall_connection_type_east", "wall_connection_type_north", "wall_connection_type_south", "wall_connection_type_west", "wall_post_bit"],
        "minecraft:polished_tuff_wall": ["wall_connection_type_east", "wall_connection_type_north", "wall_connection_type_south", "wall_connection_type_west", "wall_post_bit"],
        "minecraft:mud_brick_wall": ["wall_connection_type_east", "wall_connection_type_north", "wall_connection_type_south", "wall_connection_type_west", "wall_post_bit"],
        // 足場
        "minecraft:scaffolding": ["stability", "stability_check"],
        // はしご
        "minecraft:ladder": ["facing_direction"],
        // ライト系
        "minecraft:torch": ["torch_facing_direction"],
        "minecraft:soul_torch": ["torch_facing_direction"],
        "minecraft:redstone_torch": ["torch_facing_direction"],
        "minecraft:lantern": ["hanging_bit"],
        "minecraft:soul_lantern": ["hanging_bit"],
        "minecraft:copper_bulb": ["powered_bit", "lit"],
        "minecraft:exposed_copper_bulb": ["powered_bit", "lit"],
        "minecraft:weathered_copper_bulb": ["powered_bit", "lit"],
        "minecraft:oxidized_copper_bulb": ["powered_bit", "lit"],
        "minecraft:waxed_copper_bulb": ["powered_bit", "lit"],
        "minecraft:waxed_exposed_copper_bulb": ["powered_bit", "lit"],
        "minecraft:waxed_weathered_copper_bulb": ["powered_bit", "lit"],
        "minecraft:waxed_oxidized_copper_bulb": ["powered_bit", "lit"],
        // シーピクルス
        "minecraft:sea_pickle": ["dead_bit", "candle_count"],
        // 焚き火
        "minecraft:campfire": ["minecraft:cardinal_direction", "extinguished_bit"],
        "minecraft:soul_campfire": ["minecraft:cardinal_direction", "extinguished_bit"],
        // キャンドル
        "minecraft:candle": ["lit", "candles"],
        "minecraft:white_candle": ["lit", "candles"],
        "minecraft:light_gray_candle": ["lit", "candles"],
        "minecraft:gray_candle": ["lit", "candles"],
        "minecraft:black_candle": ["lit", "candles"],
        "minecraft:brown_candle": ["lit", "candles"],
        "minecraft:red_candle": ["lit", "candles"],
        "minecraft:orange_candle": ["lit", "candles"],
        "minecraft:yellow_candle": ["lit", "candles"],
        "minecraft:lime_candle": ["lit", "candles"],
        "minecraft:green_candle": ["lit", "candles"],
        "minecraft:cyan_candle": ["lit", "candles"],
        "minecraft:light_blue_candle": ["lit", "candles"],
        "minecraft:blue_candle": ["lit", "candles"],
        "minecraft:purple_candle": ["lit", "candles"],
        "minecraft:magenta_candle": ["lit", "candles"],
        "minecraft:pink_candle": ["lit", "candles"],
        // 本
        "minecraft:lectern": ["powered_bit", "minecraft:cardinal_direction"],
        "minecraft:chiseled_bookshelf": ["direction", "books_stored"],
        // ツール系
        "minecraft:anvil": ["damage", "minecraft:cardinal_direction"],
        "minecraft:grindstone": ["direction", "attachment"],
        "minecraft:stonecutter_block": ["minecraft:cardinal_direction"],
        "minecraft:bell": ["direction", "toggle_bit", "attachment"],
        "minecraft:loom": ["direction"],
        "minecraft:beehive": ["direction", "honey_level"],
        "minecraft:bee_nest": ["direction", "honey_level"],
        "minecraft:respawn_anchor": ["respawn_anchor_charge"],
        "minecraft:barrel": ["facing_direction", "open_bit"],
        "minecraft:cauldron": ["full_level", "cauldron_liquid"],
        "minecraft:composter": ["composter_full_level"],
        // その他
        "minecraft:end_rod": ["facing_direction"],
        "minecraft:lightning_rod": ["facing_direction"],
        "minecraft:chain": ["pillar_axis"],
        //看板
        "minecraft:standing_sign": ["ground_sign_direction"],
        "minecraft:spruce_standing_sign": ["ground_sign_direction"],
        "minecraft:birch_standing_sign": ["ground_sign_direction"],
        "minecraft:jungle_standing_sign": ["ground_sign_direction"],
        "minecraft:acacia_standing_sign": ["ground_sign_direction"],
        "minecraft:darkoak_standing_sign": ["ground_sign_direction"],
        "minecraft:mangrove_standing_sign": ["ground_sign_direction"],
        "minecraft:bamboo_standing_sign": ["ground_sign_direction"],
        "minecraft:crimson_standing_sign": ["ground_sign_direction"],
        "minecraft:warped_standing_sign": ["ground_sign_direction"],
        "minecraft:cherry_standing_sign": ["ground_sign_direction"],
        "minecraft:oak_hanging_sign": ["facing_direction", "attached_bit", "ground_sign_direction", "hanging"],
        "minecraft:spruce_hanging_sign": ["facing_direction", "attached_bit", "ground_sign_direction", "hanging"],
        "minecraft:birch_hanging_sign": ["facing_direction", "attached_bit", "ground_sign_direction", "hanging"],
        "minecraft:jungle_hanging_sign": ["facing_direction", "attached_bit", "ground_sign_direction", "hanging"],
        "minecraft:acacia_hanging_sign": ["facing_direction", "attached_bit", "ground_sign_direction", "hanging"],
        "minecraft:dark_oak_hanging_sign": ["facing_direction", "attached_bit", "ground_sign_direction", "hanging"],
        "minecraft:mangrove_hanging_sign": ["facing_direction", "attached_bit", "ground_sign_direction", "hanging"],
        "minecraft:bamboo_hanging_sign": ["facing_direction", "attached_bit", "ground_sign_direction", "hanging"],
        "minecraft:crimson_hanging_sign": ["facing_direction", "attached_bit", "ground_sign_direction", "hanging"],
        "minecraft:warped_hanging_sign": ["facing_direction", "attached_bit", "ground_sign_direction", "hanging"],
        "minecraft:cherry_hanging_sign": ["facing_direction", "attached_bit", "ground_sign_direction", "hanging"],
        // レール
        "minecraft:rail": ["rail_direction"],
        "minecraft:golden_rail": ["rail_data_bit", "rail_direction"],
        "minecraft:detector_rail": ["rail_data_bit", "rail_direction"],
        "minecraft:activator_rail": ["rail_data_bit", "rail_direction"],
        //レバー
        "minecraft:lever": ["lever_direction", "open_bit"],
        // ボタン
        "minecraft:stone_button": ["button_pressd_bit", "facing_direction"],
        "minecraft:wooden_button": ["button_pressd_bit", "facing_direction"],
        "minecraft:spruce_button": ["button_pressd_bit", "facing_direction"],
        "minecraft:birch_button": ["button_pressd_bit", "facing_direction"],
        "minecraft:jungle_button": ["button_pressd_bit", "facing_direction"],
        "minecraft:acacia_button": ["button_pressd_bit", "facing_direction"],
        "minecraft:dark_oak_button": ["button_pressd_bit", "facing_direction"],
        "minecraft:mangrove_button": ["button_pressd_bit", "facing_direction"],
        "minecraft:cherry_button": ["button_pressd_bit", "facing_direction"],
        "minecraft:warped_button": ["button_pressd_bit", "facing_direction"],
        "minecraft:crimson_button": ["button_pressd_bit", "facing_direction"],
        "minecraft:polished_blackstone_button": ["button_pressd_bit", "facing_direction"],
        "minecraft:bamboo_button": ["button_pressd_bit", "facing_direction"],
        "minecraft:stone_pressure_plate": ["redstone_signal"],
        "minecraft:wooden_pressure_plate": ["redstone_signal"],
        "minecraft:spruce_pressure_plate": ["redstone_signal"],
        "minecraft:birch_pressure_plate": ["redstone_signal"],
        "minecraft:jungle_pressure_plate": ["redstone_signal"],
        "minecraft:acacia_pressure_plate": ["redstone_signal"],
        "minecraft:dark_oak_pressure_plate": ["redstone_signal"],
        "minecraft:mangrove_pressure_plate": ["redstone_signal"],
        "minecraft:cherry_pressure_plate": ["redstone_signal"],
        "minecraft:warped_pressure_plate": ["redstone_signal"],
        "minecraft:crimson_pressure_plate": ["redstone_signal"],
        "minecraft:polished_blackstone_pressure_plate": ["redstone_signal"],
        "minecraft:bamboo_pressure_plate": ["redstone_signal"],
        "minecraft:light_weighted_pressure_plate": ["redstone_signal"],
        "minecraft:heavy_weighted_pressure_plate": ["redstone_signal"],
        // トリップワイヤーフック
        "minecraft:tripwire_hook": ["attached_bit", "drection", "powered_bit"],
        // tnt
        "minecraft:tnt": ["allow_underwater_bit", "explode_bit"],
        // 額縁
        "minecraft:frame": ["facing_direction", "item_frame_map_bit", "item_frame_photo_bit"],
        "minecraft:glow_frame": ["facing_direction", "item_frame_map_bit", "item_frame_photo_bit"],
        // 頭
        "minecraft:player_head": ["facing_direction"],
        "minecraft:zombie_head": ["facing_direction"],
        "minecraft:creeper_head": ["facing_direction"],
        "minecraft:dragon_head": ["facing_direction"],
        "minecraft:skeleton_skull": ["facing_direction"],
        "minecraft:wither_skeleton_skull": ["facing_direction"],
        "minecraft:piglin_head": ["facing_direction"],
        // 耕地
        "minecraft:farmland": ["moisturized_amount"],
        // カボチャ
        "minecraft:pumpkin": ["minecraft:cardinal_direction"],
        "minecraft:carved_pumpkin": ["minecraft:cardinal_direction"],
        "minecraft:lit_pumpkin": ["minecraft:cardinal_direction"],
        // 雪
        "minecraft:snow_layer": ["covered_bit", "height"],
        // アメジスト
        "minecraft:amethyst_cluster": ["minecraft:block_face"],
        "minecraft:large_amethyst_bud": ["minecraft:block_face"],
        "minecraft:medium_amethyst_bud": ["minecraft:block_face"],
        "minecraft:small_amethyst_bud": ["minecraft:block_face"],
        "minecraft:pointed_dripstone": ["hanging", "dripstone_thickness"],
        // エンドポータルフレーム
        "minecraft:end_portal_frame": ["end_portal_eye_bit", "minecraft:cardinal_direction"],
        // トライヤルスポナー
        "minecraft:trial_spawner": ["trial_spawner_state", "ominous"],
        "minecraft:vault": ["vault_state", "ominous", "minecraft:cardinal_direction"],
        // スカルク
        "minecraft:sculk_shrieker": ["active", "can_summon"],
        "minecraft:sculk_catalyst": ["bloom"],
        "minecraft:sculk_sensor": ["powered_bit", "skulk_sensor_phase"],
        "minecraft:calibrated_sculk_sensor": ["skulk_sensor_phase", "minecraft:cardinal_direction"],
        // 苗木
        "minecraft:oak_sapling": ["age_bit"],
        "minecraft:spruce_sapling": ["age_bit"],
        "minecraft:birch_sapling": ["age_bit"],
        "minecraft:jungle_sapling": ["age_bit"],
        "minecraft:acacia_sapling": ["age_bit"],
        "minecraft:dark_oak_sapling": ["age_bit"],
        "minecraft:mangrove_propagule": ["hanging", "propagule_stage"],
        "minecraft:cherry_sapling": ["age_bit"],
        "minecraft:bamboo_sapling": ["age_bit"],
        // 竹
        "minecraft:bamboo": ["bamboo_stalk_thickness", "age_bit", "bamboo_leaf_size"],
        // 葉
        "minecraft:oak_leaves": ["persistent_bit", "update_bit"],
        "minecraft:spruce_leaves": ["persistent_bit", "update_bit"],
        "minecraft:birch_leaves": ["persistent_bit", "update_bit"],
        "minecraft:jungle_leaves": ["persistent_bit", "update_bit"],
        "minecraft:acacia_leaves": ["persistent_bit", "update_bit"],
        "minecraft:dark_oak_leaves": ["persistent_bit", "update_bit"],
        "minecraft:mangrove_leaves": ["persistent_bit", "update_bit"],
        "minecraft:cherry_leaves": ["persistent_bit", "update_bit"],
        "minecraft:azalea_leaves": ["persistent_bit", "update_bit"],
        "minecraft:azalea_leaves_flowered": ["persistent_bit", "update_bit"],
        // つた
        "minecraft:vine": ["vine_direction_bits"],
        "minecraft:weeping_vines": ["weeping_vines_age"],
        "minecraft:twisting_vines": ["twisting_vines_age"],
        "minecraft:glow_lichen": ["multi_face_direction_bits"],
        "minecraft:sculk_vein": ["multi_face_direction_bits"],
        // ドリップリーフ
        "minecraft:big_dripleaf": ["big_dripleaf_tilt", "minecraft:cardinal_direction", "big_dripleaf_head"],
        "minecraft:small_dripleaf_block": ["upper_block_bit", "minecraft:cardinal_direction"],
        // 怪しげなブロック
        "minecraft:suspicious_sand": ["hanging", "brushed_progress"],
        "minecraft:suspicious_gravel": ["hanging", "brushed_progress"],
        // 飾り壷
        "minecraft:decorated_pot": ["drection"],
        // 種
        "minecraft:wheat": ["growth"],
        "minecraft:pumpkin_stem": ["facing_direction", "growth"],
        "minecraft:melon_stem": ["facing_direction", "growth"],
        "minecraft:beetroot": ["growth"],
        "minecraft:carrots": ["growth"],
        "minecraft:potatoes": ["growth"],
        "minecraft:sweet_berry_bush": ["growth"],
        "minecraft:cave_vines": ["growing_plant_age"],
        "minecraft:cocoa": ["age", "direction"],
        "minecraft:torchflower_crop": ["growth"],
        "minecraft:pitcher_crop": ["upper_block_bit", "growth"],
    }
}