// 必要ないステータスを除外する
export const excludedStates = [
    "top_slot_bit", "stone_slab_type", "stone_slab_type_2", "stone_slab_type_3",
    "stone_slab_type_4", "wall_block_type", "wood_type", "sapling_type",
    "old_log_type", "new_log_type", "chisel_type", "color", "coral_color",
    "dirt_type", "flower_type", "double_plant_type", "monster_egg_stone_type",
    "old_leaf_type", "new_leaf_type", "prismarine_block_type", "sand_type", "sand_stone_type",
    "stone_type", "stone_brick_type", "tall_grass_type", "structure_void_type"
];

// ブロックごとにステータスの一部を除外する
export const blockSpecificExclusions = {
    "minecraft:campfire": ["direction"],
    "minecraft:soul_campfire": ["direction"],
    "minecraft:pumpkin": ["direction"],
    "minecraft:carved_pumpkin": ["direction"],
    "minecraft:lit_pumpkin": ["direction"],
    "minecraft:lectern": ["direction"],
    "minecraft:unpowered_repeater": ["direction"],
    "minecraft:powered_repeater": ["direction"],
    "minecraft:unpowered_comparator": ["direction"],
    "minecraft:powered_comparator": ["direction"],
    "minecraft:anvil": ["direction"],
    "minecraft:chipped_anvil": ["direction"],
    "minecraft:damaged_anvil": ["direction"],
    "minecraft:calibrated_sculk_sensor": ["direction"],
    "minecraft:end_portal_frame": ["direction"],
    "minecraft:big_dripleaf": ["direction"],
    "minecraft:small_dripleaf_block": ["direction"],
    "minecraft:pink_petals": ["direction"],
    "minecraft:fence_gate": ["direction"],
    "minecraft:spruce_fence_gate": ["direction"],
    "minecraft:birch_fence_gate": ["direction"],
    "minecraft:jungle_fence_gate": ["direction"],
    "minecraft:acacia_fence_gate": ["direction"],
    "minecraft:dark_oak_fence_gate": ["direction"],
    "minecraft:mangrove_fence_gate": ["direction"],
    "minecraft:cherry_fence_gate": ["direction"],
    "minecraft:pale_oak_fence_gate": ["direction"],
    "minecraft:bamboo_fence_gate": ["direction"],
    "minecraft:warped_fence_gate": ["direction"],
    "minecraft:crimson_fence_gate": ["direction"],
    "minecraft:wooden_door": ["direction"],
    "minecraft:spruce_door": ["direction"],
    "minecraft:birch_door": ["direction"],
    "minecraft:jungle_door": ["direction"],
    "minecraft:acacia_door": ["direction"],
    "minecraft:dark_oak_door": ["direction"],
    "minecraft:mangrove_door": ["direction"],
    "minecraft:cherry_door": ["direction"],
    "minecraft:bamboo_door": ["direction"],
    "minecraft:iron_door": ["direction"],
    "minecraft:crimson_door": ["direction"],
    "minecraft:warped_door": ["direction"],
    "minecraft:copper_door": ["direction"],
    "minecraft:exposed_copper_door": ["direction"],
    "minecraft:weathered_copper_door": ["direction"],
    "minecraft:oxidzed_copper_door": ["direction"],
    "minecraft:waxed_copper_door": ["direction"],
    "minecraft:waxed_exposed_copper_door": ["direction"],
    "minecraft:waxed_weathered_copper_door": ["direction"],
    "minecraft:waxed_oxidized_copper_door": ["direction"],
    "minecraft:furnace": ["facing_direction"],
    "minecraft:blast_furnace": ["facing_direction"],
    "minecraft:smoker": ["facing_direction"],
    "minecraft:chest": ["facing_direction"],
    "minecraft:trapped_chest": ["facing_direction"],
    "minecraft:ender_chest": ["facing_direction"],
    "minecraft:stonecutter_block": ["facing_direction"],
    "minecraft:amethyst_cluster": ["facing_direction"],
    "minecraft:large_amethyst_bud": ["facing_direction"],
    "minecraft:medium_amethyst_bud": ["facing_direction"],
    "minecraft:small_amethyst_bud": ["facing_direction"],
    "minecraft:observer": ["facing_direction"],
    // ブロックごと除外
    "minecraft:bed": ["direction", "head_piece_bit", "occupied_bit"],
};