export const excludedstates = {
    "PC": {
        "blocks": {
            "minecraft:campfire": ["direction"],
            "minecraft:soul_campfire": ["direction"],
            "minecraft:pumpkin": ["direction"],
            "minecraft:carved_pumpkin": ["direction"],
            "minecraft:lit_pumpkin": ["direction"],
            "minecraft:lectern": ["direction"],
            "minecraft:unpowered_repeater": ["direction"],
            "minecraft:powered_repeater": ["direction"],
            "minecraft:unpowered_comparator": ["direction"],
            "minecraft:powered_comparator": ["direction"],
            "minecraft:calibrated_sculk_sensor": ["direction"],
            "minecraft:end_portal_frame": ["direction"],
            "minecraft:big_dripleaf": ["direction"],
            "minecraft:small_dripleaf_block": ["direction"],
            "minecraft:pink_petals": ["direction"],
            "minecraft:fence_gate": ["direction"],
            "minecraft:spruce_fence_gate": ["direction"],
            "minecraft:birch_fence_gate": ["direction"],
            "minecraft:jungle_fence_gate": ["direction"],
            "minecraft:acacia_fence_gate": ["direction"],
            "minecraft:dark_oak_fence_gate": ["direction"],
            "minecraft:mangrove_fence_gate": ["direction"],
            "minecraft:cherry_fence_gate": ["direction"],
            "minecraft:pale_oak_fence_gate": ["direction"],
            "minecraft:bamboo_fence_gate": ["direction"],
            "minecraft:warped_fence_gate": ["direction"],
            "minecraft:crimson_fence_gate": ["direction"],
            "minecraft:wooden_door": ["direction"],
            "minecraft:spruce_door": ["direction"],
            "minecraft:birch_door": ["direction"],
            "minecraft:jungle_door": ["direction"],
            "minecraft:acacia_door": ["direction"],
            "minecraft:dark_oak_door": ["direction"],
            "minecraft:mangrove_door": ["direction"],
            "minecraft:cherry_door": ["direction"],
            "minecraft:bamboo_door": ["direction"],
            "minecraft:iron_door": ["direction"],
            "minecraft:crimson_door": ["direction"],
            "minecraft:warped_door": ["direction"],
            "minecraft:copper_door": ["direction"],
            "minecraft:exposed_copper_door": ["direction"],
            "minecraft:weathered_copper_door": ["direction"],
            "minecraft:oxidzed_copper_door": ["direction"],
            "minecraft:waxed_copper_door": ["direction"],
            "minecraft:waxed_exposed_copper_door": ["direction"],
            "minecraft:waxed_weathered_copper_door": ["direction"],
            "minecraft:waxed_oxidized_copper_door": ["direction"],
            "minecraft:furnace": ["facing_direction"],
            "minecraft:blast_furnace": ["facing_direction"],
            "minecraft:smoker": ["facing_direction"],
            "minecraft:chest": ["facing_direction"],
            "minecraft:trapped_chest": ["facing_direction"],
            "minecraft:ender_chest": ["facing_direction"],
            "minecraft:stonecutter_block": ["facing_direction"],
            "minecraft:amethyst_cluster": ["facing_direction"],
            "minecraft:large_amethyst_bud": ["facing_direction"],
            "minecraft:medium_amethyst_bud": ["facing_direction"],
            "minecraft:small_amethyst_bud": ["facing_direction"],
            "minecraft:observer": ["facing_direction"],
        },
        "states": [
            "top_slot_bit",
        ],
    },
    "Mobile": {
        "blocks": {
            "minecraft:campfire": ["minecraft:cardinal_direction"],
            "minecraft:soul_campfire": ["minecraft:cardinal_direction"],
            "minecraft:pumpkin": ["minecraft:cardinal_direction"],
            "minecraft:carved_pumpkin": ["minecraft:cardinal_direction"],
            "minecraft:lit_pumpkin": ["minecraft:cardinal_direction"],
            "minecraft:lectern": ["minecraft:cardinal_direction"],
            "minecraft:unpowered_repeater": ["minecraft:cardinal_direction"],
            "minecraft:powered_repeater": ["minecraft:cardinal_direction"],
            "minecraft:unpowered_comparator": ["minecraft:cardinal_direction"],
            "minecraft:powered_comparator": ["minecraft:cardinal_direction"],
            "minecraft:calibrated_sculk_sensor": ["minecraft:cardinal_direction"],
            "minecraft:end_portal_frame": ["minecraft:cardinal_direction"],
            "minecraft:big_dripleaf": ["minecraft:cardinal_direction"],
            "minecraft:small_dripleaf_block": ["minecraft:cardinal_direction"],
            "minecraft:pink_petals": ["minecraft:cardinal_direction"],
            "minecraft:fence_gate": ["minecraft:cardinal_direction"],
            "minecraft:spruce_fence_gate": ["minecraft:cardinal_direction"],
            "minecraft:birch_fence_gate": ["minecraft:cardinal_direction"],
            "minecraft:jungle_fence_gate": ["minecraft:cardinal_direction"],
            "minecraft:acacia_fence_gate": ["minecraft:cardinal_direction"],
            "minecraft:dark_oak_fence_gate": ["minecraft:cardinal_direction"],
            "minecraft:mangrove_fence_gate": ["minecraft:cardinal_direction"],
            "minecraft:cherry_fence_gate": ["minecraft:cardinal_direction"],
            "minecraft:pale_oak_fence_gate": ["minecraft:cardinal_direction"],
            "minecraft:bamboo_fence_gate": ["minecraft:cardinal_direction"],
            "minecraft:warped_fence_gate": ["minecraft:cardinal_direction"],
            "minecraft:crimson_fence_gate": ["minecraft:cardinal_direction"],
            "minecraft:wooden_door": ["minecraft:cardinal_direction"],
            "minecraft:spruce_door": ["minecraft:cardinal_direction"],
            "minecraft:birch_door": ["minecraft:cardinal_direction"],
            "minecraft:jungle_door": ["minecraft:cardinal_direction"],
            "minecraft:acacia_door": ["minecraft:cardinal_direction"],
            "minecraft:dark_oak_door": ["minecraft:cardinal_direction"],
            "minecraft:mangrove_door": ["minecraft:cardinal_direction"],
            "minecraft:cherry_door": ["minecraft:cardinal_direction"],
            "minecraft:bamboo_door": ["minecraft:cardinal_direction"],
            "minecraft:iron_door": ["minecraft:cardinal_direction"],
            "minecraft:crimson_door": ["minecraft:cardinal_direction"],
            "minecraft:warped_door": ["minecraft:cardinal_direction"],
            "minecraft:copper_door": ["minecraft:cardinal_direction"],
            "minecraft:exposed_copper_door": ["minecraft:cardinal_direction"],
            "minecraft:weathered_copper_door": ["minecraft:cardinal_direction"],
            "minecraft:oxidzed_copper_door": ["minecraft:cardinal_direction"],
            "minecraft:waxed_copper_door": ["minecraft:cardinal_direction"],
            "minecraft:waxed_exposed_copper_door": ["minecraft:cardinal_direction"],
            "minecraft:waxed_weathered_copper_door": ["minecraft:cardinal_direction"],
            "minecraft:waxed_oxidized_copper_door": ["minecraft:cardinal_direction"],
            "minecraft:furnace": ["minecraft:cardinal_direction"],
            "minecraft:blast_furnace": ["minecraft:cardinal_direction"],
            "minecraft:smoker": ["minecraft:cardinal_direction"],
            "minecraft:chest": ["minecraft:cardinal_direction"],
            "minecraft:trapped_chest": ["minecraft:cardinal_direction"],
            "minecraft:ender_chest": ["minecraft:cardinal_direction"],
            "minecraft:stonecutter_block": ["minecraft:cardinal_direction"],
            "minecraft:amethyst_cluster": ["minecraft:block_face"],
            "minecraft:large_amethyst_bud": ["minecraft:block_face"],
            "minecraft:medium_amethyst_bud": ["minecraft:block_face"],
            "minecraft:small_amethyst_bud": ["minecraft:block_face"],
            "minecraft:observer": ["minecraft:facing_direction"],
        },
        "states": [
            "minecraft:vertical_half",
        ],
    },
    "default": {
        "blocks": {
            "minecraft:anvil": ["direction"],
            "minecraft:chipped_anvil": ["direction"],
            "minecraft:damaged_anvil": ["direction"],
            // ブロックごと除外
            "minecraft:bed": ["direction", "head_piece_bit", "occupied_bit"],
        },
        "states": [
            "stone_slab_type", "stone_slab_type_2", "stone_slab_type_3",
            "stone_slab_type_4", "wall_block_type", "wood_type", "sapling_type",
            "old_log_type", "new_log_type", "chisel_type", "color", "coral_color",
            "dirt_type", "flower_type", "double_plant_type", "monster_egg_stone_type",
            "old_leaf_type", "new_leaf_type", "prismarine_block_type", "sand_type", "sand_stone_type",
            "stone_type", "stone_brick_type", "tall_grass_type", "structure_void_type", "output_lit_bit",
        ],
    }
}

export const states_result_blocks = {
    // 向き指定
    "minecraft:chest": { "facing_direction": [2, 3, 4, 5], },
    "minecraft:trapped_chest": { "facing_direction": [2, 3, 4, 5], },
    "minecraft:ender_chest": { "facing_direction": [2, 3, 4, 5], },
    "minecraft:furnace": { "facing_direction": [2, 3, 4, 5], },
    "minecraft:blast_furnace": { "facing_direction": [2, 3, 4, 5], },
    "minecraft:smoker": { "facing_direction": [2, 3, 4, 5], },
    "minecraft:ladder": { "facing_direction": [2, 3, 4, 5], },
    "minecraft:wall_banner": { "facing_direction": [2, 3, 4, 5], },
    "minecraft:wall_sign": { "facing_direction": [2, 3, 4, 5], },
    "minecraft:spruce_wall_sign": { "facing_direction": [2, 3, 4, 5], },
    "minecraft:birch_wall_sign": { "facing_direction": [2, 3, 4, 5], },
    "minecraft:jungle_wall_sign": { "facing_direction": [2, 3, 4, 5], },
    "minecraft:acacia_wall_sign": { "facing_direction": [2, 3, 4, 5], },
    "minecraft:darkoak_wall_sign": { "facing_direction": [2, 3, 4, 5], },
    "minecraft:mangrove_wall_sign": { "facing_direction": [2, 3, 4, 5], },
    "minecraft:cherry_wall_sign": { "facing_direction": [2, 3, 4, 5], },
    "minecraft:bamboo_wall_sign": { "facing_direction": [2, 3, 4, 5], },
    "minecraft:crimson_wall_sign": { "facing_direction": [2, 3, 4, 5], },
    "minecraft:warped_wall_sign": { "facing_direction": [2, 3, 4, 5], },
    // レール系
    "minecraft:golden_rail": { "rail_direction": [0, 1, 2, 3, 4, 5] },
    "minecraft:detector_rail": { "rail_direction": [0, 1, 2, 3, 4, 5] },
    "minecraft:activator_rail": { "rail_direction": [0, 1, 2, 3, 4, 5] },
    // 成長段階
    "minecraft:cocoa": { "age": [0, 1, 2] },
    "minecraft:nether_wart": { "age": [0, 1, 2, 3] },
    "minecraft:chorus_flower": { "age": [0, 1, 2, 3, 4, 5] },
    "minecraft:pink_petals": { "growth": [0, 1, 2, 3] },
    "minecraft:wildflowers": { "growth": [0, 1, 2, 3] },
    "minecraft:leaf_litter": { "growth": [0, 1, 2, 3] },
}